### ISSUE TITLE
Makefile:22: erlang.mk: No such file or directory

### ISSUE THREAD

**Issue by zagorulkinde** [ninenines/cowboy#837] opened 2015-06-17 19:09 UTC
Hello i believe that problem with my configuration but i do the following:

Dmitrys-MacBook-Pro:Erlang Dmitry$ git clone https://github.com/ninenines/cowboy.git
Cloning into 'cowboy'...
remote: Counting objects: 7368, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 7368 (delta 3), reused 0 (delta 0), pack-reused 7354
Receiving objects: 100% (7368/7368), 5.57 MiB | 216.00 KiB/s, done.
Resolving deltas: 100% (4346/4346), done.
Checking connectivity... done.

Dmitrys-MacBook-Pro:Erlang Dmitry$ cd cowboy/
Dmitrys-MacBook-Pro:cowboy Dmitry$ ls
AUTHORS         LICENSE         ROADMAP.md      doc             rebar.config
CHANGELOG.md    Makefile        all.sh          erlang.mk       src
CONTRIBUTING.md README.md       build.config    examples        test
Dmitrys-MacBook-Pro:cowboy Dmitry$
Dmitrys-MacBook-Pro:cowboy Dmitry$ make
 DEP    cowlib
/bin/sh: line 0: [: 0: unary operator expected
 DEP    ranch
/bin/sh: line 0: [: 0: unary operator expected
 ERLC   cow_cookie.erl cow_date.erl cow_hpack.erl cow_http.erl cow_http2.erl cow_http_hd.erl cow_http_te.erl cow_mimetypes.erl cow_multipart.erl cow_qs.erl cow_spdy.erl cow_ws.erl
 APP    cowlib.app.src
 ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_listener_sup.erl ranch_protocol.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
 APP    ranch.app.src
 ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clock.erl cowboy_constraints.erl cowboy_handler.erl cowboy_http2.erl cowboy_loop.erl cowboy_middleware.erl cowboy_protocol.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_spdy.erl cowboy_static.erl cowboy_stream.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_tls.erl cowboy_websocket.erl
 APP    cowboy.app.src
Dmitrys-MacBook-Pro:cowboy Dmitry$ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0

Dmitrys-MacBook-Pro:cowboy Dmitry$ bash -v
export JAVA_HOME=$(/usr/libexec/java_home -v1.7)
/usr/libexec/java_home -v1.7
export GLASSFISH_HOME=/usr/local/opt/glassfish/libexec
export PATH=${PATH}:${GLASSFISH_HOME}/bin

Dmitrys-MacBook-Pro:cowboy Dmitry$ cd examples/hello_world/
Dmitrys-MacBook-Pro:hello_world Dmitry$ make
 DEP    cowboy
/bin/sh: line 0: [: 0: unary operator expected
Makefile:22: erlang.mk: No such file or directory
make[1]: *** No rule to make target `erlang.mk'.  Stop.
make: *** [deps] Error 2
Dmitrys-MacBook-Pro:hello_world Dmitry$ ls ../../ | grep erlang.mk
erlang.mk

What wrong with my configuration?

Thanks!

**Comment by essen** [comment] 2015-06-17 19:17
cat Makefile in the examples/hello_world/?

**Comment by zagorulkinde** [comment] 2015-06-17 19:18
mitrys-MacBook-Pro:hello_world Dmitry$ cat Makefile
PROJECT = hello_world
DEPS = cowboy
dep_cowboy = git https://github.com/ninenines/cowboy master
include ../../erlang.mk
Dmitrys-MacBook-Pro:hello_world Dmitry$ pwd
/Users/Dmitry/Developer/Erlang/cowboy/examples/hello_world

**Comment by essen** [comment] 2015-06-17 19:22
Considering it says this *after* erlang.mk was loaded, I don't think the problem is in your configuration. I think "/bin/sh: line 0: [: 0: unary operator expected" might have something to do with it. I will boot up an OSX and check if I get the same.

**Comment by essen** [comment] 2015-06-17 19:43
Aaaaah it's this issue. OK I know about it, it's tracked in: https://github.com/ninenines/erlang.mk/issues/262

I will work on getting it fixed soon.

**Comment by zagorulkinde** [comment] 2015-06-17 19:55
Thank you!

**Comment by essen** [comment] 2015-06-18 15:31
Currently testing the fix. Just a couple more hours and we'll know!

**Comment by essen** [comment] 2015-06-18 19:01
The fix is in erlang.mk, now need to update Cowboy. Feel free to update it locally it should work fine.

**Comment by zagorulkinde** [comment] 2015-06-18 19:22
The same issue i think:

Dmitrys-MacBook-Pro:Erlang Dmitry$ rm -rf cowboy/
Dmitrys-MacBook-Pro:Erlang Dmitry$
Dmitrys-MacBook-Pro:Erlang Dmitry$ git clone https://github.com/ninenines/cowboy.git
Cloning into 'cowboy'...
remote: Counting objects: 7368, done.
remote: Total 7368 (delta 0), reused 0 (delta 0), pack-reused 7368
Receiving objects: 100% (7368/7368), 5.57 MiB | 481.00 KiB/s, done.
Resolving deltas: 100% (4348/4348), done.
Checking connectivity... done.
Dmitrys-MacBook-Pro:Erlang Dmitry$
Dmitrys-MacBook-Pro:Erlang Dmitry$ ls
cowboy    n2o       r2xml     zraft_lib
Dmitrys-MacBook-Pro:Erlang Dmitry$ cd cowboy/
Dmitrys-MacBook-Pro:cowboy Dmitry$ ls
AUTHORS         LICENSE         ROADMAP.md      doc             rebar.config
CHANGELOG.md    Makefile        all.sh          erlang.mk       src
CONTRIBUTING.md README.md       build.config    examples        test
Dmitrys-MacBook-Pro:cowboy Dmitry$
Dmitrys-MacBook-Pro:cowboy Dmitry$ make
 DEP    cowlib
/bin/sh: line 0: [: 0: unary operator expected
 DEP    ranch
/bin/sh: line 0: [: 0: unary operator expected
 ERLC   cow_cookie.erl cow_date.erl cow_hpack.erl cow_http.erl cow_http2.erl cow_http_hd.erl cow_http_te.erl cow_mimetypes.erl cow_multipart.erl cow_qs.erl cow_spdy.erl cow_ws.erl
 APP    cowlib.app.src
 ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_listener_sup.erl ranch_protocol.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
 APP    ranch.app.src
 ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clock.erl cowboy_constraints.erl cowboy_handler.erl cowboy_http2.erl cowboy_loop.erl cowboy_middleware.erl cowboy_protocol.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_spdy.erl cowboy_static.erl cowboy_stream.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_tls.erl cowboy_websocket.erl
 APP    cowboy.app.src
Dmitrys-MacBook-Pro:cowboy Dmitry$ cd examples/hello_world/
Dmitrys-MacBook-Pro:hello_world Dmitry$ make
 DEP    cowboy
/bin/sh: line 0: [: 0: unary operator expected
Makefile:22: erlang.mk: No such file or directory
make[1]: *** No rule to make target `erlang.mk'.  Stop.
make: *** [deps] Error 2

**Comment by essen** [comment] 2015-06-18 19:23
Yes like I said I didn't update erlang.mk in Cowboy yet. You can add a step after "cd cowboy" and do "make erlang-mk" to update it manually.

**Comment by zagorulkinde** [comment] 2015-06-18 19:29
Thank you! now it's works fine!

**Comment by essen** [comment] 2015-06-18 19:30
Cool I'll update properly later and then close this ticket. Thanks!

**Comment by lc3t35** [comment] 2015-07-10 06:51
make erlang-mk
git clone https://github.com/ninenines/erlang.mk .erlang.mk.build
Cloning into '.erlang.mk.build'...
remote: Counting objects: 3993, done.
remote: Total 3993 (delta 4), reused 4 (delta 4), pack-reused 3988
Receiving objects: 100% (3993/3993), 1.08 MiB | 371.00 KiB/s, done.
Resolving deltas: 100% (2418/2418), done.
Checking connectivity... done.
if [ -f build.config ]; then cp build.config .erlang.mk.build; fi
cd .erlang.mk.build && make
awk 'FNR==1 && NR!=1{print ""}1' core/core.mk core/deps.mk plugins/protobuffs.mk core/erlc.mk core/docs.mk core/test.mk plugins/asciidoc.mk plugins/bootstrap.mk plugins/c_src.mk plugins/ci.mk plugins/ct.mk plugins/dialyzer.mk plugins/elvis.mk plugins/erlydtl.mk plugins/escript.mk plugins/eunit.mk plugins/relx.mk plugins/shell.mk plugins/triq.mk plugins/xref.mk plugins/cover.mk \
		| sed 's/^ERLANG_MK_VERSION = .*/ERLANG_MK_VERSION = 1.2.0-631-g56cbd9e-dirty/' > erlang.mk
cp .erlang.mk.build/erlang.mk ./erlang.mk
rm -rf .erlang.mk.build
pc10:cowboy laurent$ make
 DEP    ranch
Unknown or invalid dependency: . Please consult the erlang.mk README for instructions.
make: *** [/***/cowboy/deps/ranch] Error 78

**Comment by essen** [comment] 2015-07-10 08:06
Unrelated, in your case you just need to update Cowboy to 1.0.2 or the head of 1.0.x. Reason it breaks is my own stupidity.

**Comment by lc3t35** [comment] 2015-07-10 12:32
````
git checkout 1.0.2
Note: checking out '1.0.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 79aa25c... Update Cowboy to 1.0.2
pc10:cowboy laurent$ make
 DEP    ranch
xargs: illegal option -- r
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
 ERLC   cow_cookie.erl cow_date.erl cow_hpack.erl cow_http.erl cow_http2.erl cow_http_hd.erl cow_http_te.erl cow_mimetypes.erl cow_multipart.erl cow_qs.erl cow_spdy.erl cow_ws.erl
 APP    cowlib.app.src
 ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_listener_sup.erl ranch_protocol.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
 APP    ranch.app.src
 ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clock.erl cowboy_handler.erl cowboy_http.erl cowboy_http_handler.erl cowboy_loop_handler.erl cowboy_middleware.erl cowboy_protocol.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_spdy.erl cowboy_static.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_websocket.erl cowboy_websocket_handler.erl
src/cowboy_protocol.erl:272: undefined macro 'INLINE_LOWERCASE/9'
src/cowboy_protocol.erl:397: undefined macro 'INLINE_LOWERCASE/4'
src/cowboy_protocol.erl:257: function parse_hd_name/8 undefined
src/cowboy_protocol.erl:369: function parse_host/3 undefined
src/cowboy_protocol.erl:275: function parse_hd_name_ws/8 is unused
src/cowboy_protocol.erl:282: function wait_hd_before_value/8 is unused
src/cowboy_protocol.erl:295: function parse_hd_before_value/8 is unused
src/cowboy_protocol.erl:314: function wait_hd_value/9 is unused
src/cowboy_protocol.erl:329: function wait_hd_value_nl/9 is unused
src/cowboy_protocol.erl:343: function parse_hd_value/9 is unused
make[1]: *** [ebin/cowboy.app] Error 1
make: *** [all] Error 2
pc10:cowboy laurent$ git checkout 1.0.1
Previous HEAD position was 79aa25c... Update Cowboy to 1.0.2
HEAD is now at 3d90780... Update Cowboy to 1.0.1
pc10:cowboy laurent$ make
 APP    cowlib.app.src
 APP    ranch.app.src
 ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clock.erl cowboy_handler.erl cowboy_http.erl cowboy_http_handler.erl cowboy_loop_handler.erl cowboy_middleware.erl cowboy_protocol.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_spdy.erl cowboy_static.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_websocket.erl cowboy_websocket_handler.erl
src/cowboy_protocol.erl:272: undefined macro 'INLINE_LOWERCASE/9'
src/cowboy_protocol.erl:397: undefined macro 'INLINE_LOWERCASE/4'
src/cowboy_protocol.erl:257: function parse_hd_name/8 undefined
src/cowboy_protocol.erl:369: function parse_host/3 undefined
src/cowboy_protocol.erl:275: function parse_hd_name_ws/8 is unused
src/cowboy_protocol.erl:282: function wait_hd_before_value/8 is unused
src/cowboy_protocol.erl:295: function parse_hd_before_value/8 is unused
src/cowboy_protocol.erl:314: function wait_hd_value/9 is unused
src/cowboy_protocol.erl:329: function wait_hd_value_nl/9 is unused
src/cowboy_protocol.erl:343: function parse_hd_value/9 is unused
make: *** [ebin/cowboy.app] Error 1
pc10:cowboy laurent$ make clean
 GEN    clean
 GEN    clean-app
 GEN    clean-ct
pc10:cowboy laurent$ make
 APP    cowlib.app.src
 APP    ranch.app.src
 ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clock.erl cowboy_handler.erl cowboy_http.erl cowboy_http_handler.erl cowboy_loop_handler.erl cowboy_middleware.erl cowboy_protocol.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_spdy.erl cowboy_static.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_websocket.erl cowboy_websocket_handler.erl
src/cowboy_protocol.erl:272: undefined macro 'INLINE_LOWERCASE/9'
src/cowboy_protocol.erl:397: undefined macro 'INLINE_LOWERCASE/4'
src/cowboy_protocol.erl:257: function parse_hd_name/8 undefined
src/cowboy_protocol.erl:369: function parse_host/3 undefined
src/cowboy_protocol.erl:275: function parse_hd_name_ws/8 is unused
src/cowboy_protocol.erl:282: function wait_hd_before_value/8 is unused
src/cowboy_protocol.erl:295: function parse_hd_before_value/8 is unused
src/cowboy_protocol.erl:314: function wait_hd_value/9 is unused
src/cowboy_protocol.erl:329: function wait_hd_value_nl/9 is unused
src/cowboy_protocol.erl:343: function parse_hd_value/9 is unused
make: *** [ebin/cowboy.app] Error 1
````

**Comment by essen** [comment] 2015-07-13 22:17
Wait, were you using Cowboy *master* before? If so then the issue is elsewhere and I gave you bad advice.

**Comment by lc3t35** [comment] 2015-07-14 07:39
yep master, Master !

**Comment by essen** [comment] 2015-07-14 09:38
Ok then I will get back to you after I get home.

-- 
Loïc Hoguin
http://ninenines.eu

-------- Original Message --------

**Comment by essen** [comment] 2015-07-25 17:24
Sorry I only started working a few days ago, did you fix your issue? I believe I saw that myself and pushed a fix yesterday.

Closing, if still a problem please reopen.

**Closed by essen** 2015-07-25 17:24 UTC
