### ISSUE TITLE
Performance regression between cowboy 1.0.4 and 2.7.0?

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/cowboy#1410] opened 2019-10-29 20:20 UTC
We're (finally) upgrading our code to use cowboy 2.7.0 (from cowboy 1.0.4) and I'm concerned about what looks like a performance regression.

Using `cowboy_static`, 1.0.4 achieves ~10,000 requests / second. 2.7.0 achieves only ~6500-7000 rps.

I'm seeing similar performance impact for a relatively simple handler that just generates a small chunk of JSON. 1.0.4 achieves ~55Krps; 2.7.0 achieves ~40Krps.

Both instances are using ranch 1.7.1.

Testing was done with `wrk -d 10 -t 16 -c 1000 http://localhost:8080/` (with `.../foo.json` for the JSON response).

Am I missing something in configuration, or how I'm benchmarking, or is there a genuine issue here? Is there any way I can help figure this out?

**Comment by essen** [comment] 2019-10-29 20:40
You should see a small hit, but this sounds a bit much. What are the `max_keepalive` and `linger_timeout` values? To make Cowboy 2.x behave the same as 1.x you'll need to set `linger_timeout` to 0.

**Comment by rlipscombe** [comment] 2019-10-29 20:49
> What are the ... values?

Unset, so defaults.

I'll do some more investigation tomorrow and see if I can repro this with a smaller example.

**Comment by essen** [comment] 2019-10-29 20:54
Yeah then probably related to `linger_timeout`. It's a feature introduced in 2.x but it has a negative effect on synthetic benchmarks. Looking forward to hearing more.

**Comment by rlipscombe** [comment] 2019-10-31 13:23
Assuming I'm setting it correctly...

```
    {ok, _Pid} = cowboy:start_clear(cowboy_perf_http,
                                    [{port, 8104}],
                                    #{env => #{dispatch => Dispatch},
                                      linger_timeout => 0}),
```

...then it doesn't make any difference: 2.7.0 is still significantly slower in this test than 1.0.4 (7Krps vs 9Krps with cowboy_static, on the same hardware).

On further investigation, for our purposes, 7Krps is still plenty, so I'm going to continue with the upgrade, but I thought this might bear looking at.

**Comment by essen** [comment] 2019-10-31 15:55
Yeah I'll take a look when I can.

**Comment by rlipscombe** [comment] 2019-11-01 10:59
Thanks.

**Comment by essen** [comment] 2019-12-03 11:56
Related: https://stressgrid.com/blog/cowboy_performance/ cc @petrohi

A quick analysis shows that almost 8% of the time is spent in `Transport:setopts`. This is due to Cowboy having to use active mode instead of passive for socket operations to be able to receive other messages and implement the interface required by HTTP/2.

It currently uses `{active,once}` because `{active,N}` was not available in `ssl` until I sent a PR. That PR is part of the OTP 21.3 release. I suppose it would be a good idea to start using it, although this means we will only support OTP 21.3 and above. Some experiment can definitely be done at least.

Other likely culprits include `maps:get` taking almost 1% and there's probably more time lost due to better handling HTTP parsing and not having done an optimization session since doing those changes. But nothing stands out as much as `Transport:setopts`.

**Comment by rlipscombe** [comment] 2019-12-03 15:44
> although this means we will only support OTP 21.3 and above

We're using 22.1, so that'd work for us, but ultimately it's your call how many prior releases of OTP you want to support.

**Comment by essen** [comment] 2019-12-03 19:07
It's fine but I might just go for 22+ for simplicity.

**Comment by essen** [comment] 2019-12-05 15:16
So it's not really that Cowboy 2 is slower than Cowboy 1. Cowboy 2 is actually much faster (at least with `active_n` anyway)! But because Cowboy 2 uses a separate process per request by default this adds some necessary overhead. Necessary because we can't really do otherwise for HTTP/2.

In order to get the most performance out of Cowboy 2, you have to not use `cowboy_stream_h` and instead use your own stream handler. If that's not possible, you can try the new `persistent_term` functionality to see if that improves anything. My suspicion is that copying between processes is the biggest responsible for the performance drop (and the Req can indeed be large and a new one gets copied for every request). The environment is also copied for every requests and that would avoid that. In order to avoid copying of the Req, it would be interesting to try a VM built with the `--enable-sharing-preserving` option.

A hello world stream handler that gives better performance than Cowboy 1.x and Cowboy 2.

``` erlang
-module(fast_stream_h).
-behavior(cowboy_stream).

-export([init/3]).
-export([data/4]).
-export([info/3]).
-export([terminate/3]).
-export([early_error/5]).

-spec init(cowboy_stream:streamid(), cowboy_req:req(), cowboy:opts())
	-> {[{spawn, pid(), timeout()}], any()}.
init(_StreamID, Req0, Opts) ->
	%% Simulate finding the handler for a closer 1:1 comparison.
	Env = maps:get(env, Opts, #{}),
	{ok, Req, #{handler := toppage_h}} = cowboy_router:execute(Req0, Env),
	Body = <<"Hello world!">>,
	Headers = #{
		<<"content-length">> => integer_to_binary(byte_size(Body)),
		<<"content-type">> => <<"text/plain">>
	},
	{[{response, 200, cowboy_req:response_headers(Headers, Req), Body}, stop], undefined}.

-spec data(cowboy_stream:streamid(), cowboy_stream:fin(), cowboy_req:resp_body(), State)
	-> {cowboy_stream:commands(), State} when State::any().
data(StreamID, IsFin, Data, Next) ->
	cowboy_stream:data(StreamID, IsFin, Data, Next).

-spec info(cowboy_stream:streamid(), any(), State)
	-> {cowboy_stream:commands(), State} when State::any().
info(StreamID, Info, Next) ->
	cowboy_stream:info(StreamID, Info, Next).

-spec terminate(cowboy_stream:streamid(), cowboy_stream:reason(), any()) -> any().
terminate(StreamID, Reason, Next) ->
	cowboy_stream:terminate(StreamID, Reason, Next).

-spec early_error(cowboy_stream:streamid(), cowboy_stream:reason(),
	cowboy_stream:partial_req(), Resp, cowboy:opts()) -> Resp
	when Resp::cowboy_stream:resp_command().
early_error(StreamID, Reason, PartialReq, Resp, Opts) ->
	cowboy_stream:early_error(StreamID, Reason, PartialReq, Resp, Opts).
```

Configured like this:

``` erlang
{ok, _} = cowboy:start_clear(http, [{port, 8080}], #{
    env ⇒ #{dispatch ⇒ Dispatch},
    max_keepalive ⇒ infinity,
    stream_handlers ⇒ [fast_stream_h]
}),
```

I see numbers as follow:

Cowboy 1.1.x:

```
Running 10s test @ http://localhost:8080
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.09ms    2.12ms  43.98ms   93.27%
    Req/Sec    75.22k     4.61k   82.23k    74.00%
  1497032 requests in 10.06s, 185.60MB read
Requests/sec: 148810.25
Transfer/sec:     18.45MB
```

Cowboy 2 `active_n`:

```
Running 10s test @ http://localhost:8080
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.29ms    2.30ms  41.05ms   93.16%
    Req/Sec    58.03k     6.85k   72.64k    70.20%
  1151143 requests in 10.02s, 142.72MB read
Requests/sec: 114850.21
Transfer/sec:     14.24MB
```

Cowboy 2 `active_n` with the above stream handler:

```
Running 10s test @ http://localhost:8080
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   598.49us    1.03ms  33.43ms   95.59%
    Req/Sec    91.87k     4.46k   97.64k    82.00%
  1829427 requests in 10.06s, 226.81MB read
Requests/sec: 181941.98
Transfer/sec:     22.56MB
```

So if you really need to squeeze better HTTP/1.1 performance it seems that Cowboy 2 is your best bet (at least `active_n` is), only you're going to have to deal with an asynchronous programming model instead of Cowboy 1's synchronous model.

Same is obviously true for HTTP/2, via stream handlers you remove a lot of overhead. I don't know about Websocket though, since the overhead is only for establishing the connection.

The guide might benefit from an extended section about squeezing every bit of performance out of Cowboy 2. But that should probably be reserved for very specific applications.

**Comment by rlipscombe** [comment] 2019-12-05 15:19
Interesting. Thanks for the pointers.

**Comment by essen** [comment] 2019-12-05 15:34
I can confirm I see a big improvement from `active_n` over master. Without `active_n` the performance is closer to that of Cowboy 1.1.x (a little better than 1.1.x thanks to stream handlers). So I'd expect a boost in the next Cowboy version once `active_n` gets merged.

More to come after this week-end as a new batch of benchmarks should be available then.

**Comment by essen** [comment] 2019-12-05 15:50
I do not think it's about copying the Req between processes anymore. I just tried with a minimal Req and the numbers are still low.

**Comment by essen** [comment] 2020-01-06 12:03
So Cowboy now uses `active,N` via https://github.com/ninenines/cowboy/commit/db0d6f8d254f2cc01bd458dc41969e0b96991cc3

However I will not close this ticket yet; I want to document how to start a performance chapter in the guide and document the stream handler approach to some extent.

**Comment by essen** [comment] 2020-01-06 13:05
I've added a skeleton chapter to the guide. I will push it later today. Closing, thanks!

**Closed by essen** 2020-01-06 13:05 UTC

**Comment by donileo** [comment] 2020-01-06 17:37
Current master branch still keeps the synchronous model through `cowboy_stream_h` right? 

In the case of using something like Phoenix, if I were to use my own stream handler and bypass `cowboy_stream_h` would Phoenix also require changes to work async with cowboy? Kind of curious to know what function the modification would need to take place in (assuming and hoping its only one function).

**Comment by essen** [comment] 2020-01-06 19:46
The synchronous model is here to stay, it's fine for the vast majority of applications. I only recommend going with a stream handler approach for the few routes that really require it.

About Phoenix, I don't really know, I've never used it. I suspect it would require changes yes. But Phoenix and Plug probably have additional overhead as well, so if you need the performance you will most likely have to write a stream handler directly for the routes that require it.
