### ISSUE TITLE
No logs on idle_timeout

### ISSUE THREAD

**Issue by hairyhum** [ninenines/cowboy#1385] opened 2019-06-17 21:00 UTC
When connection is closed becasue of `idle_timeout`, the exit signal is `shutdown`. There will be no response to the client (becasue it's presumably gone) and no explicit logs by cowboy.
Sasl logs ignore this reason as well, so there is no way to tell why the handler process stopped other than knowing that this could happen.
Probably other reason could be used, because this is not a normal exit, it's an error. Or cowboy could log a custom message in case of timeouts.

Maybe we misconfigure some logging system in RabbitMQ and the error is logged, but I can't find where it would happen.
I tried with a clean cowboy project with just sasl logs enabled and there was no log message on `idle_timeout`

Related to the issue addressed in [rabbitmq management](https://github.com/rabbitmq/rabbitmq-management/pull/711)
Related to #1278

**Comment by essen** [comment] 2019-09-05 12:31
It's an error in a sense but not an error caused by the user's code and that's why there are no logs. As far as the server is concerned everything is working as intended. Producing a non-normal exit reason or logging could create very large logs very quickly because these kinds of errors are quite common overall (not necessarily `idle_timeout` but timeouts in general).

That said, a stream handler can be implemented to catch all those. In the case of `idle_timeout` the reason passed to the `terminate` callback will be `{connection_error, timeout, 'Connection idle longer than configuration allows.'}` and should be obvious enough logged as-is. The same is true for all exit reasons in Cowboy, and it'll also tell you which part of the RFC to look at if applicable. Do note that stream handlers are only called when the request headers were successfully received, so some errors currently never make it to stream handlers. Maybe they should, I don't know.

Closing, thanks!

**Closed by essen** 2019-09-05 12:31 UTC

**Comment by hairyhum** [comment] 2019-09-05 13:16
Thanks for clarification. I couldn't find that error description in the docs though. Is it mentioned there? Should it be mentioned there?

**Comment by essen** [comment] 2019-09-05 13:20
The docs don't go that far, at least not yet: https://ninenines.eu/docs/en/cowboy/2.6/manual/cowboy_stream/#_reason

All erroneous reasons include the human readable atom though and that part is documented.

**Comment by hairyhum** [comment] 2019-09-05 15:56
Maybe documentation just needs some links, because I wouldn't discover `cowboy_stream` docs from here: https://ninenines.eu/docs/en/cowboy/2.6/guide/handlers/ or here: https://ninenines.eu/docs/en/cowboy/2.6/manual/cowboy_http2/
I can create a PR, but I'm not sure how do I link function reference from the user guide.

**Comment by essen** [comment] 2019-09-05 16:02
In the Advanced part of the guide you have https://ninenines.eu/docs/en/cowboy/2.6/guide/streams/ but it's pretty bare bone. Haven't been able to allocate time on that yet.
