### ISSUE TITLE
err_content_length_mismatch error in Chrome

### ISSUE THREAD

**Issue by theom** [ninenines/cowboy#889] opened 2015-09-07 02:19 UTC
Hi

With reference to bug #722. (I'm filing a new issue since that one is closed)

I am seeing the exact same behavior, that is, chrome reports an ERR_CONTENT_LENGTH_MISMATCH error for content larger than roughly 32KB. I say roughly because the file needs to be larger than 33.304 bytes for the error to reliably show. I'm using cowboy 1.0.1 (also tried 1.0.3) and OTP18.

To reproduce the error, configure a simple cowboy instance with the following static route:

  {"/[...]",  cowboy_static,  {priv_dir, my_app,  "some_directory"}}

Then load a file larger than 33.304 bytes while monitoring the network tab in the developer tools window. Note that you have to wait at least 5 seconds for the error to show up in the status column.

To figure out the file size that reliably triggers the error I did some testing by loading various different file sizes (nothing fancy here - I just hammered away at F5 for each file). Following is a list of file sizes in bytes and the approximate failure rate for each file:

Bytes    Failure Rate
32.768  0
32.769  0
32.776  0
33.024  0
33.152  1%
33.280  1%, then multiple fails in a row until it showed correctly again
33.304  1%, then multiple fails in a row until it showed correctly again
33.305  ~50%
33.306  100%
33.408  100%

I noticed that cowboy version 1.0.3 had been released so I upgraded and ran the tests again with the same results.

Hope this helps to track this down.

**Comment by essen** [comment] 2015-09-07 07:11
Does it still happen if you set the linger transport option?

**Comment by theom** [comment] 2015-09-07 12:36
Not sure if I'm setting linger correctly but I get the same results.

I added {linger, {true, 1}} to the transport options list in cowboy:start_http. Is that correct?

Doesn't this error come up when the server 'prematurely' closes the connection?

Since you seem to be hinting that the problem might lie on the OS side I'd like to mention that I'm running this on FreeBSD.

**Comment by essen** [comment] 2015-09-07 12:42
It's just a guess, and I suggest something more like `{linger, {true, 30000}}`. It's a possible issue with Cowboy currently where it closes the connection before the buffers are sent in some conditions.

I experimented with a fix a while ago, with a combination of linger option and other things, and didn't come up with a satisfying enough result. I believe the architecture in Cowboy 2 will allow me to deal with this much more easily.

**Comment by theom** [comment] 2015-09-07 13:32
`{linger {true, 30000}}` had no effect.

This is quite a crippling bug since I can't serve files larger than 32KB. I tried this on Linux and it works correctly there so this is clearly FreeBSD (or BSD) specific.

I might give Cowboy 2 a try. How close to production ready is it?

**Comment by essen** [comment] 2015-09-07 13:38
I haven't merged the changes I was trying yet so it's not in Cowboy 2 yet. Which itself passes tests, but will see many interface changes still.

It does look like system specific, because I have a harder time to reproduce in my environments, and usually under some kind of load only.

The trick is that, before closing the connection, you try to read from the socket for some time (say 30s max) to let the buffers empty. When the read call returns an error or timeouts, you're done.

But again, just making guesses here, it would be good to know what Chrome receives exactly to confirm that this is the issue.

**Comment by theom** [comment] 2015-09-07 14:00
In my tests I used a regular text file and hence could very rapidly see when only part of the file had been received. When the error comes up the last 20 or 30 characters were missing. I didn't count how many were missing but the number varied a bit and it cycled randomly through the same sized chunks of missing characters on subsequent refreshes.

In reading about similar problems like this there always seems to be the suggestion to use shutdown instead of close when closing the socket. Did you try that in your experiments? I tried changing close(Socket) to shutdown(Socket, read) in ranch_tcp:close just to try this out but it didn't help.

**Comment by essen** [comment] 2015-09-07 14:34
OK so it's most certainly the same issue.

The way it goes is like this:

* shutdown the write side after you are done sending (the shutdown will be sent after everything else)
* _wait_

And that's where it gets trickier, because we can't know the client received everything for sure. That's why instead of just waiting, you can read from the socket until there's either an error or a timeout (and if there's data, you have to ignore the data and read again). It's basically the linger option except it actually works.

That's at least how I've seen it done in places.

This works for sure, but introduces other issues in that it potentially closes the socket much later, and that's what I didn't manage to solve yet. Ideally you would only enable this wait behavior if there's been a large enough amount of data sent, not if you just sent a 400 error because you couldn't parse the request, and not if the response fits in one TCP frame (like most HTTP responses that don't have a body).

In Cowboy 2 I will have a central point where the data goes through and I will be able to make informed decisions about enabling this behavior or not, something I cannot do right now, or at least not with complete certainty that everything would be fixed.

As far as cowboy_static is concerned, a workaround timer:sleep(5000) in cowboy_static:rest_terminate would most likely work, if you want to try.

**Comment by theom** [comment] 2015-09-07 14:57
Sleeping in cowboy_rest:rest_terminate only prolonged the wait until the error comes up in the browser (5 s wait without the sleep, 10 s wait with sleep(5000)).

I tried increasing the send buffer on the OS side by running:

`sysctl -w net.inet.tcp.sendspace=65536`

and that solved the problem, but of course only for files smaller than 64KB. This might work for me since my application will mainly use websockets for communication with the server and I can configure the buffer to hold my largest file. I'll then have to see if I run into the same problem on the websocket side.

Thanks for all the suggestions and I'm looking forward to version 2 :)

**Comment by essen** [comment] 2015-09-07 15:00
If sleeping doesn't help, Your particular problem might be related to something else.

Normally when you send data the OS waits for a threshold to be passed before the data buffered in the socket is actually sent over the network.

To avoid this issue we made `{nodelay, true}` the default, but it sounds like it doesn't work for your case?

**Comment by ferd** [comment] 2015-09-07 15:03
The weird thing about this being related to the send buffer size is that usually, Erlang (and indirectly cowboy) should be able to block the sender by descheduling it when the send buffer is full so that you don't overflow things.
The OS will wait until the data has been sent, but if the other end of the connection never accepts, then the data can never actually be sent -- a TCPdump will reveal this quickly by observing window sizes.

The two big options there are:

1. on freeBSD, Erlang doesn't do proper detection of full send buffers 
2. something with the client is wrong and it stops accepting content, stalling the connection.

2) is easy to prove/disprove, and in all likelihood, the issue could be with 1).

**Comment by theom** [comment] 2015-09-07 15:36
Well, I think I can definitely say the problem is on the server side since I see the same behavior in Chrome and FF so 2) is out.

As far as socket buffers in Erlang on FreeBSD I really can't say but the problem clearly exists there and it could be something like option 1).

Since increasing the buffer size to get this to 'semi' work doesn't feel right I'm seriously considering switching to Linux.

**Comment by essen** [comment] 2015-09-07 16:05
Regardless of moving to Linux, it would be interesting to understand what's going on. At the very least, if you could setup a git repository that demonstrates the issue reliably, then others can try to understand what's going on.

I have a FreeBSD VM so I will be able to take a look, though probably not before next week-end at the earliest as I'll be away for a few days.

**Comment by theom** [comment] 2015-09-07 16:22
Ok, I'll see what I can do.

**Comment by theom** [comment] 2015-09-07 18:42
This is interesting.

I created a new Cowboy app having exactly the same route as before (just the static file route) and I don't get the error! The only difference from before is I don't depend on Bullet. Could it be the case that Bullet is somehow interfering with the http server?

I'll have to examine this a bit more to figure out the exact difference between these two setups.

**Comment by essen** [comment] 2015-09-07 18:44
That would be very surprising for Bullet to do that.

**Comment by theom** [comment] 2015-09-07 18:44
Ah, I forgot - I had increased the buffer way larger than the 32KB file I was testing.

The error remains.

**Comment by essen** [comment] 2015-09-07 18:46
:-)

**Comment by theom** [comment] 2015-09-07 19:19
I created the following repository which should demonstrate the problem:

https://github.com/theom/eclm

**Comment by essen** [comment] 2015-09-07 21:23
Thanks. I'll look when I can, don't delete it. :-)

**Comment by theom** [comment] 2015-09-07 21:24
No worries - I'll keep the repository around.

**Comment by theom** [comment] 2015-09-08 10:40
I added a very simple TCP server and a slow client to the eclm repository in an attempt to further test the buffer behavior.

It turns out that the client always receives all the data from the server, regardless of sent data size, and even if the server has long closed the socket. I haven't looked at how you do the send in Cowboy (or Ranch I guess), but I think it's clear that you are doing it a bit differently than I am. Anyway, sockets in Erlang on FreeBSD aren't completely broken :)

**Comment by essen** [comment] 2015-09-08 13:10
In the static handler we use file:sendfile for TCP connections, and an emulated version with ssl:send for SSL connections.

**Comment by theom** [comment] 2015-09-08 20:31
If I use file:sendfile instead of gen_tcp:send the client only receives data 1.5 times the send buffer size. Strangely though, from time to time it receives 4 times the buffer size.

I also tried using the raw file version of file:sendfile but with the same results. It always hangs when it has sent the same 1.5 times the buffer size.

This all is unrelated to when the server closes the socket. Even if I delay closing, the client just waits, doing nothing, until the socket is closed by the server.

It seems like file:sendfile is seriously broken on FreeBSD.

**Comment by essen** [comment] 2015-09-08 20:47
What Erlang version is this? I think there was issues with particular Erlang versions.

Also try with disabling async pool threads, 'erl +A 0' I believe.

**Comment by theom** [comment] 2015-09-08 21:18
I'm using OTP 18 (erts-7.0).

Disabling the async pool had no effect.

You probably noticed that I sent an email to the Erlang bug list in the hope that someone might have seen this before (and have a solution). If not and this is an Erlang bug it would be great if it can be fixed in the next release.

**Comment by dumbbell** [comment] 2015-09-09 09:08
Hi!

I'm going to take a look too, as it could hit me in the near future.

FWIW, `file:sendfile/{2,5}` does not use async threads by default anymore since Erlang 17.0, because of this problem:
http://erlang.org/pipermail/erlang-bugs/2013-October/003818.html

**Comment by theom** [comment] 2015-09-09 20:48
That's great. I'd love to hear the results you get.

Please note that if you use my eclm server/client you'll have to uncomment/comment the right set of code in the recv_loop of the server to switch between file:sendfile/2 and file:sendfile/5.

**Comment by theom** [comment] 2015-09-11 01:28
I believe I have found and fixed the bug.

The sendfile C call in erts was misbehaving for some strange reason. Tuncer Ayaz got in touch with me since he implemented the FreeBSD version of sendfile and he pointed me to the right places in the code to look for problems.

I will submit a patch for this to the Erlang team in the next few days.

**Comment by essen** [comment] 2015-09-11 07:59
Good to know. :-)

Thanks you and Tuncer!

**Comment by theom** [comment] 2015-09-12 18:12
I've submitted a pull request for the patch to the erlang-bugs list.

I think we can close this issue now as this is not a bug in Cowboy.

**Comment by essen** [comment] 2015-09-12 18:49
Great job, thanks!

**Closed by essen** 2015-09-12 18:49 UTC

**Comment by dumbbell** [comment] 2015-09-13 13:47
@theom: Thank you very much! I haven't had time to look at it yet.
