### ISSUE TITLE
Multipart Uploads Stalling in Cowboy 2.7.0

### ISSUE THREAD

**Issue by robertlong** [ninenines/cowboy#1442] opened 2020-03-04 23:43 UTC
We recently upgraded our Phoenix application using Cowboy 2.6.3 to 2.7.0. We are noticing that a large number of medium size file uploads (30mb and larger) are stalling before they finish uploading. Downgrading to 2.6.3 fixed our issue. I'm reading through the migration guide, but I don't think I see anything relating to this issue. Did I miss some additional configuration that would cause these stalled uploads?

**Comment by essen** [comment] 2020-03-05 08:05
Try master see if the issue is there as well. Also please provide the protocol used, based on what you say it could be the HTTP/1.1 flow control added in 2.7.0. But things have changed significantly since 2.7.0 so this might already be fixed in master.

**Comment by essen** [comment] 2020-04-08 08:33
This might have been fixed by the changes in https://github.com/ninenines/cowboy/commit/4ab69f402e38f77b7612ecf30f3defe9c6a76d24

Please try master and see if that helps. Reopen with a test case if there's still an issue.

Also note that if the client uploads too fast without reading from the socket and the server is trying to send you a response the buffers might get full which ends up blocking, see `send_timeout` option for `gen_tcp`.

**Closed by essen** 2020-04-08 08:33 UTC

**Comment by Shemeikka** [comment] 2021-06-16 07:38
Hi,

We are experiencing this when using TLS and Cowboy 2.7+. Large file uploads (1GB+) will be shown as failed and stalled in Chrome and Firefox, and when using Curl, the response is `curl: (56) Unexpected EOF`.

Everything works if TLS is not used. However, if we use TLS and Cowboy 2.6.3, then uploading large files works.

Test file can be generated using command `fallocate -l 10G gentoo_root.img`. Uploading the file can be done using command `curl -F 'file=@gentoo_root.img' <URL>`.

How we configure Cowboy in our Elixir project. Certificates are generated using [mkcert](https://github.com/FiloSottile/mkcert).

```elixir
# Configuring Cowboy in Elixir project's application.ex

{Plug.Cowboy,
scheme: server_options[:scheme],
plug: Knlgw.Endpoint,
options: [
    ip: server_host_ip,
    port: server_port,
    certfile: Keyword.get(server_config, :cert_file),
    keyfile: Keyword.get(server_config, :key_file),
    cacertfile: Keyword.get(server_config, :ca_cert_file),
    cipher_suite: :strong,
  ]
}
```

We use Plug.Parser for reading the multipart file upload. Those options i.e. length and others, don't have any effect on this problem.
```elixir
# Use Plug.Parser.Multipart for parsing the request body if it's multipart
plug(Plug.Parsers,
  parsers: [
    {:multipart,
     length: 100_000_000, read_length: 5_000_000, read_timeout: 60_000, send_timeout: 10_000}
  ],
  pass: ["*/*"]
)
```

Versions:
```
hexpm/elixir:1.11.2-erlang-23.1.5-alpine-3.12.1

cowboy 2.9.0
plug_cowboy 2.5.0
```
Also tried with Erlang 23.3 versions and same experience.

@essen Could this be a problem with Cowboy or with Erlang?

**Comment by essen** [comment] 2021-06-16 07:40
Please open a new ticket, and please try with the most recent version of Cowboy.
