### ISSUE TITLE
Crash with cowboy_clear:proc_lib_hack/5

### ISSUE THREAD

**Issue by lianglijin** [ninenines/cowboy#1206] opened 2017-08-21 09:20 UTC
17:06:55.642 [error] CRASH REPORT Process <0.802.0> with 0 neighbours exited with reason: bad argument in call to erlang:iolist_size(terminate) in cow_ws:payload_length/1 line 594
17:06:55.642 [error] Ranch listener http_listener terminated with reason: bad argument in call to erlang:iolist_size(terminate) in cow_ws:payload_length/1 line 594

====================================================

2017-08-21 16:59:41 =CRASH REPORT====
  crasher:
    initial call: cowboy_clear:proc_lib_hack/5
    pid: <0.804.0>
    registered_name: []
    exception exit: {{badarg,[{erlang,iolist_size,[terminate],[]},{cow_ws,payload_length,1,[{file,"/server/_build/default/lib/cowlib/src/cow_ws.erl"},{line,594}]},{cow_ws,frame,2,[{file,"/server/_build/default/lib/cowlib/src/cow_ws.erl"},{line,540}]},{cowboy_websocket,websocket_send,2,[{file,"/server/_build/default/lib/cowboy/src/cowboy_websocket.erl"},{line,372}]},{cowboy_websocket,handler_call,6,[{file,"/server/_build/default/lib/cowboy/src/cowboy_websocket.erl"},{line,342}]},{cowboy_http,loop,2,[{file,"/server/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,179}]},{cowboy_clear,proc_lib_hack,5,[{file,"/server/_build/default/lib/cowboy/src/cowboy_clear.erl"},{line,29}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},[{cowboy_clear,proc_lib_hack,5,[{file,"/server/_build/default/lib/cowboy/src/cowboy_clear.erl"},{line,34}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.774.0>,<0.773.0>,ranch_sup,<0.673.0>]
    messages: []
    links: [<0.774.0>,#Port<0.1148>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 2636
  neighbours:
2017-08-21 16:59:41 =ERROR REPORT====
Ranch listener http_listener had connection process started with cowboy_clear:start_link/4 at <0.804.0> exit with reason: {badarg,[{erlang,iolist_size,[terminate],[]},{cow_ws,payload_length,1,[{file,"/server/_build/default/lib/cowlib/src/cow_ws.erl"},{line,594}]},{cow_ws,frame,2,[{file,"/server/_build/default/lib/cowlib/src/cow_ws.erl"},{line,540}]},{cowboy_websocket,websocket_send,2,[{file,"/server/_build/default/lib/cowboy/src/cowboy_websocket.erl"},{line,372}]},{cowboy_websocket,handler_call,6,[{file,"/server/_build/default/lib/cowboy/src/cowboy_websocket.erl"},{line,342}]},{cowboy_http,loop,2,[{file,"/server/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,179}]},{cowboy_clear,proc_lib_hack,5,[{file,"/server/_build/default/lib/cowboy/src/cowboy_clear.erl"},{line,29}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

**Comment by essen** [comment] 2017-08-21 09:47
Duplicate of https://github.com/ninenines/cowboy/issues/1204

**Closed by essen** 2017-08-21 09:47 UTC

**Comment by essen** [comment] 2017-08-21 12:47
Fixed. Thanks!
