### ISSUE TITLE
start_tls fails from time to time with {:socket_error, :enotconn, ...}

### ISSUE THREAD

**Issue by albertored** [ninenines/cowboy#1078] opened 2017-01-20 15:47 UTC
I've just moved my service under https using cowboy **2.0.0-pre.5**.

Sometimes when a request comes to the server I get the following error on logs but, strange enough, the response is correctly sent. In particular I got the error only for the very first request the server receive.

`Ranch listener :http had connection process started with :cowboy_tls:start_link/4 at #PID<0.401.0> exit with reason: {:function_clause, [{:cowboy_http2, :terminate, [:undefined, {:socket_error, :enotconn, :"An error has occurred on the socket."}], [file: '/path/to/project/deps/cowboy/src/cowboy_http2.erl', line: 521]}, {:cowboy_tls, :proc_lib_hack, 5, [file: '/path/to/project/deps/cowboy/src/cowboy_tls.erl', line: 29]}]}`

I don't know if can be helpful but I'm running cowboy from elixir.

**Comment by essen** [comment] 2017-01-20 17:50
If you can reproduce it in a test environment, try tracing (with dbg) the cowboy_http2 module and paste the trace logs here.

**Comment by essen** [comment] 2017-01-22 19:22
I can see it now. I'll see if I can trace it on Tuesday.

**Comment by essen** [comment] 2017-01-22 21:44
So this occurs because `ssl:peername/1` fails saying there is no connection (while it occurs in the cowboy_http2 module, it happens before anything HTTP/2 specific runs). I'm sorry to say that I have no clue why at this point. The odd thing is, that the client connects fine and gets the page rendered properly, at least here.

**Comment by albertored** [comment] 2017-01-23 08:14
Yes, the odd thing is exactly that, also here the client connects and gets the page rendered properly.

**Comment by albertored** [comment] 2017-01-23 09:57
I don't know if it can be helpful but with dbg trace switched on the error change:

`2017-01-23 09:43:16.109 [error] Ranch listener :http had connection process started with :cowboy_tls:start_link/4 at #PID<0.415.0> exit with reason: {{:badmatch, {:error, :closed}}, [{:cowboy_http2, :preface, 1, [file: '/path/to/project/deps/cowboy/src/cowboy_http2.erl', line: 133]}, {:cowboy_http2, :init, 8, [file: '/path/to/project/deps/cowboy/src/cowboy_http2.erl', line: 108]}, {:cowboy_tls, :proc_lib_hack, 5, [file: '/path/to/project/deps/cowboy/src/cowboy_tls.erl', line: 29]}]}`

The function `cowboy_http2:preface/1` has not an error matching for the return state of `Transport:send(Socket, cow_http2:settings(Settings)).`

**Comment by essen** [comment] 2017-01-23 11:26
It's probably the same issue except the socket was closed (or close was detected) a tiny bit later as sending the preface is the next thing we do.

**Comment by halturin** [comment] 2017-03-06 08:17
just got the same behavior

19:47:08.852 [error] CRASH REPORT Process <0.702.0> with 0 neighbours exited with reason: no function clause matching cowboy_http2:terminate(undefined, {socket_error,enotconn,'An error has occurred on the socket.'}) line 517 in cowboy_tls:proc_lib_hack/5 line 34
19:47:08.853 [error] Ranch listener https terminated with reason: no function clause matching cowboy_http2:terminate(undefined, {socket_error,enotconn,'An error has occurred on the socket.'}) line 517

**Comment by essen** [comment] 2017-03-06 09:31
That should be fixed in most recent commit, see https://git.ninenines.eu/cowboy.git/tree/src/cowboy_http2.erl#n542

I guess I can close this. I will tag later this week. Thanks!

**Closed by essen** 2017-03-06 09:31 UTC
Labels: Bug
