### ISSUE TITLE
Child processes have no chance to terminate gracefully because of the 'kill' in cowboy_http2:stream_terminate_children/3

### ISSUE THREAD

**Issue by jinnipark** [ninenines/cowboy#1119] opened 2017-02-06 07:31 UTC
```
stream_terminate_children([{Pid, StreamID}|Tail], StreamID, Acc) ->
	exit(Pid, kill),
	stream_terminate_children(Tail, StreamID, Acc);
```

Can't we do better than this?

**Comment by essen** [comment] 2017-02-06 08:44
There is a shutdown value that is not currently implemented.

**Comment by csrl** [comment] 2017-06-29 09:04
Changing 'kill' to 'closed' allows us to be notified of closed connections.  Any drawback to doing that?  Can that be made the default here?

**Comment by essen** [comment] 2017-06-29 09:08
For you, probably not, but for the upstream code used by everyone, there's a drawback. If the user code traps exits, we risk having the process stay around indefinitely. Once the shutdown value is implemented it will act like any other supervisor.

**Comment by csrl** [comment] 2017-06-29 23:42
In our case its the cowboy_http:terminate/2 use of 'kill' that is the problem for us.  But yes, I saw the 'todo' comments in the code.  User code that trap exits must do so for a reason and should be responsible for the ramifications.  I don't think cowboy can be responsible for that.  Having the kill in place makes it impossible to properly handle closed connections.  The temporary 'kill' approach tries to fix a problem that could be fixed in the user code, but introduces a problem then that can not be fixed in the user code.  Anyway, not a big deal - it is a minor patch for us to apply temporarily.

Thanks!

**Comment by essen** [comment] 2017-06-30 00:01
Of course Cowboy has to kill eventually. That's how supervisors behave. There's no way around that. Can't leave a process hanging forever. Just need the shutdown timeout to be enforced. The default of 5 seconds ought to be enough for most use cases.

**Comment by motobob** [comment] 2017-07-25 08:57
latest `2.0.0-rc1` experience the same behaviour.  
https://github.com/ninenines/cowboy/blob/master/src/cowboy_http.erl#L1071-L1084 
what is the plan to address this?

issuing kill to a handler which can be still in the process of updating some state is bad and handler should be notified to finish gracefully but i agree with you that it should be terminated eventually.

**Comment by essen** [comment] 2017-07-25 09:07
You should not be relying on the shutdown timeout being there for your application to work properly. Your application should be able to deal with processes being killed for any reason. This will be fixed eventually, but this doesn't change that you should design your application to deal with processes being killed.

**Comment by jeremey** [comment] 2017-07-25 10:56
@essen cowboy has no value unless it is used to build *something*. It is that *something* that is responsible for doing the right thing in each situation. It is the role of the library/framework to provide tools. Being notified of client disconnect, and having the ability to control the result, is one of those (very valuable) tools. Being killed without notification is just wrong. If that's the behaviour I as the user of the library desire and choose to implement using the tool provided (i.e. being notified), so be it.

Imagine if an OS killed every process immediately that received a half-close on a TCP socket. It's ridiculous. If I want that, I'll implement it, using the tool you provide me.

**Comment by essen** [comment] 2017-07-25 11:11
Relax, this is why there's a ticket. This doesn't change the truthfulness of my statement.

**Comment by csrl** [comment] 2017-07-26 17:25
Probably it just isn't clear what the intended design is going to be, so people are voicing their concerns in the absence of understanding.  From what I'm gathering from the notes in the code and the comments here, is that proper OTP supervision is going to be employed, such that when a connection is closed, the process will be properly terminated, resulting in the 'terminate' function being called, in which the process has a chance to clean up its state.

What I'm not yet clear about is how cowboy will provide for 'tail' handling in the request lifecycle.  In other servers I've used, a request lives beyond the connection, such that any additional asynchronous tasks associated with the request may still run to completion such that log output and other activity are associated to the request, and when all tail calls complete, the final request complete event/callback is handled.  This is important for producing useful logging and other operational insight of the system, as well as just simply deterministic behavior.

**Comment by essen** [comment] 2017-07-26 17:53
First paragraph, yes, pretty much. Signal shutdown, wait for shutdown timeout and then brutal_kill the process if it still exists.

Second paragraph is out of scope. This is Erlang, if you need to have something live on after the request or the connection process exits, you do it in another process. There's nothing to add to Cowboy for this.

**Comment by essen** [comment] 2017-07-26 17:56
And to be even more clear, this first paragraph is what this ticket is about and what will be implemented in 2.0. It's already documented but is simply not implemented right now.

**Comment by essen** [comment] 2017-07-31 18:50
My thought process so far is this.

We have two different cases to handle as far as shutting down child processes go. The first case is when a stream ends (stream handler returns `stop`) while a process for that stream still exists, and the second case is when the connection process goes down.

In the normal case I am thinking of maintaining a single timer for all processes currently being shut down. The timer would be running for the next process to be shut down, and once that triggers (or if the process goes down in-between) we would reset the timer for the next process and so on. To avoid making too many timers, it's probably a good idea to group children together, for example when the timer triggers for a process, we check the list of existing processes and everything supposed to shut down in the next 50 ms (or another configurable value) gets killed at the same time if it's still alive. And every time we reset the timer, we make sure to decrement the shutdown value for all children with the time that was elapsed.

In the case where the connection is going down, we do not need to do all this, we simply want the processes to all be gone before we shut down. We can simply take the largest shutdown time amongst the remaining processes, make a timer for that time, and have a receive loop waiting for all processes to stop. Then when (and if) the timer triggers we kill everything remaining.

**Comment by essen** [comment] 2017-08-02 18:15
One thing though, processes will need to trap exit signals if they want to be able to shut down gracefully (like in a supervisor), otherwise they will be killed by the `shutdown` exit signal.

**Comment by csrl** [comment] 2017-08-05 04:09
That seems reasonable.  And if it can support 'infinity' for the timeout, just as a normal supervision tree supports, that would work for us.  I'm happy to be able to have the option to shoot myself in the foot, which is my own problem.

We manage our own ranch protocol behavior and directly call cowboy_http:init for a connection.  For each request that comes in, we may spawn additional linked/supervised processes to handle async aspects, and we need to wait for those 'tail' jobs to finish before shutting down the connection and stream processes.

As far as we are concerned, the only timeouts that we want firing from within cowboy are ones related to client (mis)behavior.  Our server implementation manages its its own concerns and we have no need for cowboy to decide that it has given the implementation long enough to execute.  I guess there are differing needs/ views on that, but I hope how we implement isn't prevented.

Thanks.

**Comment by essen** [comment] 2017-08-05 10:13
I do not think that will be a problem. I will try to remember to handle the `infinity` case, but if I forget it should be a very tiny patch.

**Comment by essen** [comment] 2017-08-07 15:15
I notice that in the current HTTP/2 code there can be many instances where processes are killed very quickly. Not just connection shutdown, unlike HTTP/1.1. All will be fixed once my changes are done.

**Comment by essen** [comment] 2017-08-08 15:13
I have just pushed 45ddcd8c67f2fc20f4d44e84b5e7e3faef0a1d58 which should fix everything. Please try it and tell me if it works for you. I will add tests at a later date.

**Comment by motobob** [comment] 2017-08-08 22:42
@essen thx. I'll try it out by the end of the week and let you know if that helps out.

**Comment by essen** [comment] 2017-08-14 15:19
Just pushed tests for this. Seems like it works as intended. I *think* we can close this ticket. Please reopen/comment if I missed something. Thanks!

**Closed by essen** 2017-08-14 15:19 UTC

**Comment by csrl** [comment] 2017-08-16 17:32
Thanks @essen.  I haven't had a chance to try this out yet, but it looks like it'll work.  I'll post back if I run into any issues.
