### ISSUE TITLE
reset idle_timeout after each write of chunk when streaming large response in fixed chunks in HTTP/1.1

### ISSUE THREAD

**Issue by thenrio** [ninenines/cowboy#1416] opened 2019-11-18 11:55 UTC
We can use now use [cowboy_req:cast](doc/src/manual/cowboy_req.cast.asciidoc) to set `idle_timeout` on a request.

As quoted in from [comments of 1278](https://github.com/ninenines/cowboy/issues/1278#issuecomment-378364131), value should be large, so that we "allows long responses to complete" or small, so that we "ensure we don't have too many zombie connections around".

When server resets the idle_timeout after each write of chunk then we could have a _medium timeout_ that "allows long responses to complete" AND "ensure we don't have too many zombie connections around"?

The proposed feature would be useful when size of response varies and we have a fixed chunk size : such as a database stream by chunk of 500 rows.

Much like in https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout:

> The timeout is set only between two successive read operations, not for the transmission of the whole response.

**Comment by essen** [comment] 2019-11-18 12:07
The nginx option you quote is a *read* timeout, just like `idle_timeout`. Only in nginx' case it's a timeout when nginx reads the origin server's response when acting as a proxy (so in this case nginx is acting as a client).

The reason there is no timeout reset on *write* is because the connection may be already gone when you write and you may end up writing for a very long time before the buffers fill up and the connection close is detected, especially with protocols such as Server-Sent Events.

So you ought to set the `idle_timeout` to the maximum duration for a request/response you allow. If you really want a timeout on write, you can always write a stream handler, but I'm not sure you'll get useful results. Still, feel free to experiment and report back if it's useful.

**Comment by thenrio** [comment] 2019-11-18 16:50
Thanks.

How do you produce "the connection may be already gone when you write and you may end up writing for a very long time before the buffers fill up and the connection close is detected"?

In my case, I have a _good_ client, but it's slow, and from what I see the tcp flow controls regulates the request more than the write buffer.

---

Before I dive into experimentation, could you also hint me on some _useful results_?

What I think I can achieve is 

* better configuration : `idle_timeout` depends on accepted time for metrics on a fixed chunk size, rather than on the full stream size.
* bad client that stops to read has it's connection killed sooner or same time (think can do that with iptables drop).

Do you have any other goal?
Thanks.

**Comment by essen** [comment] 2019-11-18 17:11
It's called the TCP half-closed (or half-open, or reset) problem. It's mentioned here with regard to HTTP: https://tools.ietf.org/html/rfc7230#section-6.6

How to reproduce, well that's a tricky one, but "pulling the plug" or "disconnecting the WiFi" tend to do it. It happens when you have an abrupt closing of the connection. The remote endpoint is no longer there, but the local endpoint believes it is.

I don't know what *useful results* means, I'm just saying if you think you need it and it helps in at least some scenarios I would consider including something. But right now I don't see it.

By the way the connection being idle is not unusual at all for HTTP, it happens in a number of cases (in-between requests with keep-alive, with expect: 100-continue, with some media types like `text/event-stream` and so on. So I don't think timeouts based on rates of incoming data are a good idea. `idle_timeout` is a timeout that resets every time there's data coming in. So if `idle_timeout` is configured to 60s and there's data coming in every 5s, the request will continue being processed forever, and that's OK because it's not a `max_request_duration_timeout`.

**Comment by thenrio** [comment] 2019-11-20 10:58
My scenario is a _large_ stream (say Size=10Mb), backed by database.
Let's say slow client needs T=2min to have the Size bytes. 

My database is postgres, the stream MUST be in a transaction (https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY), because network regulates database stream.

In this scenario, database time ~ request time.

I use ecto to connect to postgres, and I need to configure a total timeout for transaction.

Then global `idle_timeout` to T is a fit for me now: requires no code in handler, and no hairy configuration (T for this request, otherwise t).
This is was I did in my release.

"reset `idle_timeout` after each write of chunk" is not useful when you need to know in advance how much total time you need.

**Comment by essen** [comment] 2020-02-07 10:56
Closing for now, you're welcome to provide more details on how this would help. An example demonstrating how you think it'll work would be even better. Thanks!

**Closed by essen** 2020-02-07 10:56 UTC
