### ISSUE TITLE
Websocket terminated with badmatch error when sending flood of messages

### ISSUE THREAD

**Issue by oriondean** [ninenines/cowboy#917] opened 2015-11-26 16:43 UTC
I'm connecting to a RabbitMQ server through the web-stomp plugin with a websocket. I believe RabbitMQ uses a cowboy server to power the STOMP protocol it uses.

When I send a flood of messages through this websocket, the connection is closed before it finishes sending all messages.

Looking at the logs, I see the following error:
```
 {{badmatch,<<1,254,1,58,18,163,127,205,65,230,49,137,24,199,
                              26,190,102,202,17,172,102,202,16,163,40,140,30,
                              160,99,140,14,184,119,214,26,226,116,207,16,162,
                              118,169,28,162,124,215,26,163,102,142,19,168,
                              124,196,11,165,40,144,71,248,24,169,63,141,82,
                              227,63,141,82,227,63,141,82,227,63,141,82,227,
                              63,141,82,227,63,141,82,227,63,141,82,227,63,
                              141,82,227,63,141,82,227,63,141,82,227,63,141,
                              82,227,63,141,82,227,63,141,82,227,63,141,82,
                              227,63,141,82,227,63,141,82,227,63,141,82,227,
                              63,141,82,227,63,141,82,227,63,141,82,227,63,
                              141,82,227,63,141,82,227,63,141,82,227,63,141,
                              82,227,63,141,82,227,63,141,82,227,63,141,82,
                              227,63,141,82,227,63,141,82,227,63,141,82,227,
                              63,141,82,227,63,141,82,227,63,141,82,227,63,
                              141,82,227,63,141,82,227,63,141,82,227,63,141,
                              82,227,63,141,82,227,63,141,82,227,63,141,82,
                              227,63,141,82,227,63,141,82,227,63,141,82,227,
                              63,141,82,227,63,141,82,227,63,141,82,227,63,
                              141,82,227,63,141,82,227,63,141,82,227,63,141,
                              82,227,63,141,82,227,63,141,82,227,63,141,82,
                              227,63,141,82,227,63,141,82,227,63,141,82,227,
                              63,141,82,227,63,141,82,227,63,141,82,227,63,
                              141,82,227,63,141,82,227,63,141,82,227,63,141,
                              82,227,63,141,82,227,63,141,82,227>>},
                  [{cowboy_http_websocket,websocket_data,4,[]},
                   {cowboy_http_protocol,upgrade_protocol,3,[]}]}
```

This only seems to happen when sending the messages in Chrome. For some reason, Firefox and IE don't seem to cause the websocket to be closed.

Any ideas on what could be the cause behind this? Let me know if you need any more information

**Comment by essen** [comment] 2015-11-26 16:44
RabbitMQ stable uses a very old version of Cowboy. Can you try with RabbitMQ master? I updated Cowboy there. The issue is probably long gone.

**Comment by oriondean** [comment] 2015-11-26 16:59
Yep, using RabbitMQ 3.6.0 Milestone 3 version seems to have fixed i!

I was running the latest stable RabbitMQ release (3.5.6) which used Cowboy v0.5.
The pre-release version of RabbitMQ (3.6.0) now uses Cowboy v1.0.3

Just out of curiosity, would you have any idea what was fixed between the two cowboy versions to resolve this issue?

**Comment by essen** [comment] 2015-11-26 17:01
Exactly no. But since then Cowboy has been made to pass 100% of the Autobahntestsuite tests which covers everything from the RFC, so this problem was probably fixed sometimes around then.

Closing, thanks!

**Closed by essen** 2015-11-26 17:01 UTC
