### ISSUE TITLE
Crash when running a release in console mode

### ISSUE THREAD

**Issue by sidwubf** [ninenines/cowboy#857] opened 2015-07-25 02:51 UTC
Steps to reproduce:
1. Clone cowboy
2. Go to examples/hello_world
3. Run _rel/bin/hello_world_example console

Erlang crashes with the following output:

./_rel/hello_world_example/bin/hello_world_example console
Exec: /Users/siduw/Job/WenQie/erlang/cowboy/examples/hello_world/_rel/hello_world_example/erts-6.3.1/bin/erlexec -boot /Users/siduw/Job/WenQie/erlang/cowboy/examples/hello_world/_rel/hello_world_example/releases/1/hello_world_example -boot_var ERTS_LIB_DIR /Users/siduw/Job/WenQie/erlang/cowboy/examples/hello_world/_rel/hello_world_example/erts-6.3.1/../lib -env ERL_LIBS /Users/siduw/Job/WenQie/erlang/cowboy/examples/hello_world/_rel/hello_world_example/releases/1/lib -config /Users/siduw/Job/WenQie/erlang/cowboy/examples/hello_world/_rel/hello_world_example/releases/1/sys.config -args_file /Users/siduw/Job/WenQie/erlang/cowboy/examples/hello_world/_rel/hello_world_example/releases/1/vm.args -- console
Root: /Users/siduw/Job/WenQie/erlang/cowboy/examples/hello_world/_rel/hello_world_example
/Users/siduw/Job/WenQie/erlang/cowboy/examples/hello_world/_rel/hello_world_example
Erlang/OTP 17 [erts-6.3.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

=INFO REPORT==== 25-Jul-2015::10:36:56 ===
    application: cowboy
    exited: {bad_return,
                {{cowboy_app,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{cowboy_app,start,[normal,[]],[]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,272}]}]}}}}
    type: permanent
{"Kernel pid terminated",application_controller,"{application_start_failure,cowboy,{bad_return,{{cowboy_app,start,[normal,[]]},{'EXIT',{undef,[{cowboy_app,start,[normal,[]],[]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}]}}}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,cowboy,{bad_return,{{cowboy_app,start,[normal,[]]},{'EXIT',{undef,[{cowboy_app,start,[normal,[]],[]},{application_master,st

**Comment by essen** [comment] 2015-07-25 10:35
Can you show the full log including the compilation steps?

**Comment by essen** [comment] 2016-01-14 19:11
Closing as I can't reproduce and am missing steps to figure things out.

**Closed by essen** 2016-01-14 19:11 UTC
Labels: Bug

**Comment by henry-hz** [comment] 2016-03-27 11:46
the last working commit for hello_word was dbb636034f20736e16eb9d6c809217c9525b6cbd , after that I 
![cowboy](https://cloud.githubusercontent.com/assets/1010008/14065215/4ed53960-f42a-11e5-9810-c00829c2a90c.png)

[erl_crash.txt](https://github.com/ninenines/cowboy/files/190883/erl_crash.txt)

**Comment by essen** [comment] 2016-03-27 11:49
Yes on current master that's normal. Breaking changes are happening, and docs/examples have not been updated yet.

**Comment by henry-hz** [comment] 2016-03-27 11:54
thanks for the fast feedback
