### ISSUE TITLE
My weird problem again, out of file descriptors

### ISSUE THREAD

**Issue by skvamme** [ninenines/cowboy#1079] opened 2017-01-23 18:19 UTC
A new error message popped up

15:30:31.219 [warning] Ranch acceptor reducing accept rate: out of file descriptors

I think this is the same problem that I have had for a while. Just wanted to show this new error message.

**Comment by essen** [comment] 2017-01-23 18:40
This is something we have added recently to show that you are running out of file descriptors and that Ranch will stop accepting connections temporarily (it waits 100 milliseconds and then resumes normal operations, hoping that new FDs have been open).

If you see this you should probably increase the maximum number of FDs you can have on your system, If it's already large, I'll need more info.

**Comment by essen** [comment] 2017-02-04 16:53
Closing, thanks!

**Closed by essen** 2017-02-04 16:53 UTC

**Comment by sokser** [comment] 2017-03-01 21:24
We're noticing the same issue, even though the number of file descriptors for the system has been set to 65k:

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 29127
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

We, tested the open file limit manually to around 60k with no issues, however if the number reaches around 3.5-4k in elixir/phoenix the program drops all connections and logs `[warning] Ranch acceptor reducing accept rate: out of file descriptors`. We can't seem to identify the issue as we have also boosted the ERL_MAX_PORTS to 6500:

## Name of the node
-name nolimitex@127.0.0.1

## Cookie for distributed erlang
-setcookie W<|q{hpwAS__M4Z6h}fFU|4_XuQ`F>Zw>m}[mc{VUh5@%V0.[Z[(Pq~02/OzyIxE

## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
## (Disabled by default..use with caution!)
##-heart

## Enable kernel poll and a few async threads
##+K true
##+A 5

## Increase number of concurrent ports/sockets
-env ERL_MAX_PORTS 65000

## Tweak GC to run more often
##-env ERL_FULLSWEEP_AFTER 10

# Enable SMP automatically based on availability
-smp auto


Can you provide some assistance on debugging this?

**Comment by essen** [comment] 2017-03-01 21:30
This is not a bug in Cowboy (or Ranch), Ranch just shows a message when the OS refuses to give more file descriptors. If you really need help with this you can try the usual channels or get some paid help so someone can look into what you are doing directly.

**Comment by mmzeeman** [comment] 2017-03-02 06:37
One thing which might get you on your way yourself is using recon. Recon has a couple of nice tools to check what is eating your file-descriptors.

See: http://ferd.github.io/recon/ and http://www.erlang-in-anger.com

```
(ex@example)1> length(recon:tcp()).
34751
(ex@example)2> length(recon:files()).
10
```

BTW @essen, for cowboy I think it is better to crash and restart than to drop the accept rate when ranch runs out of fds. That drops all tcp connections and should open up some fds.

**Comment by essen** [comment] 2017-03-02 09:07
Crashing could lead up to not being able to re-open the listener socket because you don't have fds, which is worse.

**Comment by mmzeeman** [comment] 2017-03-02 10:37
True, I didn't think about that one. 

I still have the feeling that for http like services it is better to explicitly drop connections in situations like these. Dropping the accept rate will slow down and possibly block all new requests.

**Comment by essen** [comment] 2017-03-02 10:53
The process in question is also just the acceptor, so killing it won't open up anything. :-) Perhaps what is needed is a pluggable interface. Anyway, wrong ticket, wrong project for that.

**Comment by haslinger** [comment] 2018-07-14 16:53
Ran into the same issue with a phoenix app. My question is now, why is the running out of file descriptors happening in the first place?

**Comment by mmzeeman** [comment] 2018-07-14 18:43
OS limits?

Check `ulimit` to check what the maximum number of fd's is what you can open. Default it is only 1024.

**Comment by haslinger** [comment] 2018-07-14 19:00
Yes, I changed them meanwhile. But the app usually has approx 60 open files, so I am (or better was) super surprised by the sudden increase to 1000+. The simple reason: I have been DDOSed by a Bot.
