### ISSUE TITLE
GET timeout after POST request

### ISSUE THREAD

**Issue by jamhed** [ninenines/cowboy#833] opened 2015-06-12 20:51 UTC
Cowboy version 1.0.1

GET request terminates by timeout (15 seconds) if follows POST request.
As a work-around I just manually close HTTP connection right after POST request.

Please see HTTP messages log down here:

T 127.0.0.1:46915 -> 127.0.0.1:9080 [AP]
POST /store HTTP/1.1.
Host: localhost:9080.
Connection: keep-alive.
Content-Length: 28161.
Pragma: no-cache.
Cache-Control: no-cache.
Accept: _/_.
Origin: http://localhost:9080.
X-Requested-With: XMLHttpRequest.
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36.
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarypxEP1lB353zVwsgJ.
Referer: http://localhost:9080/.
Accept-Encoding: gzip, deflate.
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4.
.
###### 

T 127.0.0.1:9080 -> 127.0.0.1:46915 [AP]
HTTP/1.1 200 OK.
connection: keep-alive.
server: Cowboy.
date: Fri, 12 Jun 2015 20:46:04 GMT.
content-length: 0.
.
###### 

T 127.0.0.1:46915 -> 127.0.0.1:9080 [AP]
GET /store/avatar/3622058535?1434141965084 HTTP/1.1.
Host: localhost:9080.
Connection: keep-alive.
Pragma: no-cache.
Cache-Control: no-cache.
Accept: image/webp,_/_;q=0.8.
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36.
Referer: http://localhost:9080/.
Accept-Encoding: gzip, deflate, sdch.
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4.

-------------------------- 15 seconds timeout -------------------------

-------------------- Request repeated by browser -------------------
###### 

T 127.0.0.1:46917 -> 127.0.0.1:9080 [AP]
GET /store/avatar/3622058535?1434141965084 HTTP/1.1.
Host: localhost:9080.
Connection: keep-alive.
Pragma: no-cache.
Cache-Control: no-cache.
Accept: image/webp,_/_;q=0.8.
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36.
Referer: http://localhost:9080/.
Accept-Encoding: gzip, deflate, sdch.
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4.
.
## 

T 127.0.0.1:9080 -> 127.0.0.1:46917 [AP]
HTTP/1.1 200 OK.
transfer-encoding: identity.
server: Cowboy.
date: Fri, 12 Jun 2015 20:46:19 GMT.
connection: close.
content-type: image/jpeg.

**Comment by essen** [comment] 2015-07-13 22:21
Can you give the handler code for the POST and/or more info about what kind of handler and what it is doing?

**Comment by romangaleev** [comment] 2015-07-13 23:09
Sure. It is a XHR file upload request, here is the handler:
write_user_file(Store, Data, Uid, Type, Mime) when is_number(Uid) ->
   FileId = user_file_store( db_user:files(Uid, Type), Mime, Store, Uid, Type, Data),
   db_msg:sys_notify(Uid, [<<"avatar/upload">>, FileId]),
   ok.

handle_upload(Req, StorePath) ->
   Plist = multipart(Req, []),
   [Sid, Data, Mime, Type] = get_props(Plist, [sid,file,mime,type]),
   Uid = db_user:sid_to_uid(erlang:binary_to_integer(Sid)),
   write_user_file(StorePath, Data, Uid, Type, Mime),
   % cowboy_req:reply(200, Req). BUG?
   cowboy_req:reply(200, [{<<"connection">>, <<"close">>}], Req).

handle_method(<<"POST">>, Req, StorePath) -> handle_upload(Req, StorePath);
handle_method(<<"GET">>, Req, StorePath) -> handle_get(Req, StorePath);
handle_method(Method, _, _) -> ?ERR("Unhandled method: ~p", [Method]).

handle(Req, State = [StorePath]) ->
   ?INFO("web_store", []),
   {Method, Req2} = cowboy_req:method(Req),
   {ok, Req3} = handle_method(Method, Req2, StorePath),
   {ok, Req3, State}.

**Comment by romangaleev** [comment] 2015-07-13 23:14
And here is dispatcher:

dispatch_rules() ->
    cowboy_router:compile(
        [{'_', [
            {"/store/[...]",        web_store,        ["store"]},
            {"/image/[...]",        web_image,        ["store"]},
            {"/",                   cowboy_static,    {file, "web/index.html"}},
            {"/main/ws/[...]",      bullet_handler,   [{handler, ws_main}]},
            {"/[...]",              cowboy_static,    {dir, "web"}}
    ]}]).

**Comment by essen** [comment] 2015-07-14 07:13
Thanks, I will try in a few days, I have quite a backlog right now. :-)

**Comment by romangaleev** [comment] 2015-07-14 07:21
I can provide you a test server if you'd like to, with a running
application. It may simplify debugging.

On Tue, Jul 14, 2015 at 9:14 AM, Loïc Hoguin <notifications@github.com>
wrote:

> Thanks, I will try in a few days, I have quite a backlog right now. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ninenines/cowboy/issues/833#issuecomment-121149997>.
>



-- 
With best regards,
    Roman Galeev,
    +420 702 817 968

**Comment by essen** [comment] 2015-07-14 07:23
If I fail to reproduce the issue then perhaps, thanks. Today I can't work though so I will get back to you.

**Comment by jamhed** [comment] 2015-08-13 21:16
Any luck meanwhile? :)

**Comment by essen** [comment] 2015-08-13 21:22
Sorry, haven't had much time to work on Cowboy yet.

**Comment by essen** [comment] 2015-08-18 21:51
Don't see the issue, but one thing though: the only place in Cowboy with 15000 is the default socket read timeout when reading the body. Since GET has no body, guessing it's POST that has issues?

**Comment by endeepak** [comment] 2015-11-11 04:16
I'm facing similar issue and the stack trace shows

```
2015-11-10T16:56:06.680425+00:00 app[web.1]: 16:56:06.680 request_id=19c1ba3f-cfaf-476f-a145-12d234b61c55 [info] POST /stub_urls
2015-11-10T16:56:21.684018+00:00 heroku[router]: at=info method=POST path="/stub_urls" host=stubonweb.herokuapp.com request_id=19c1ba3f-cfaf-476f-a145-12d234b61c55 fwd="43.247.159.40" dyno=web.1 connect=1ms service=15004ms status=500 bytes=243
2015-11-10T16:56:21.683882+00:00 app[web.1]: 16:56:21.683 [error] #PID<0.429.0> running StubOnWeb.Endpoint terminated
2015-11-10T16:56:21.683887+00:00 app[web.1]: Server: stubonweb.herokuapp.com:80 (http)
2015-11-10T16:56:21.683888+00:00 app[web.1]: Request: POST /stub_urls
2015-11-10T16:56:21.683889+00:00 app[web.1]: ** (exit) an exception was raised:
2015-11-10T16:56:21.683890+00:00 app[web.1]:     ** (CaseClauseError) no case clause matching: {:error, :timeout}
2015-11-10T16:56:21.683891+00:00 app[web.1]:         (plug) lib/plug/parsers/urlencoded.ex:10: Plug.Parsers.URLENCODED.parse/5
2015-11-10T16:56:21.683892+00:00 app[web.1]:         (plug) lib/plug/parsers.ex:186: Plug.Parsers.reduce/6
2015-11-10T16:56:21.683893+00:00 app[web.1]:         (stub_on_web) lib/stub_on_web/endpoint.ex:1: StubOnWeb.Endpoint.phoenix_pipeline/1
2015-11-10T16:56:21.683894+00:00 app[web.1]:         (stub_on_web) lib/phoenix/endpoint/render_errors.ex:34: StubOnWeb.Endpoint.call/2
2015-11-10T16:56:21.683894+00:00 app[web.1]:         (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
2015-11-10T16:56:21.683895+00:00 app[web.1]:         (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

@essen 's last comment seems to make more sense with this stack trace and corresponding line(plug/parsers/urlencoded.ex:10) in code

![image](https://cloud.githubusercontent.com/assets/310608/11083656/2759f602-8858-11e5-91e4-74c909d1dc33.png)

Also in my case this issue started after I followed the https://github.com/phoenixframework/phoenix/issues/459#issuecomment-150965117 to read request body and added the below code in endpoint.ex

```elixir
defp copy_req_body(conn, _) do
    {:ok, body, _} = Plug.Conn.read_body(conn, length: 1_000_000_000)
    Plug.Conn.put_private(conn, :raw_request_body, body)
end
  
plug :copy_req_body

plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison
```
More context on the problem is posted on http://stackoverflow.com/questions/33637418/elixir-phoenix-on-heroku-timeout-error-after-15-seconds

Is there a way to fix this? Would increasing socket timeout solve this issue? If so, how to increase the time out?

**Comment by essen** [comment] 2015-11-11 09:08
Basically no idea what you just said, but to answer the question, yes, the timeout can be increased on a per call basis. See the manual for the body functions.

**Comment by jamhed** [comment] 2015-11-13 06:19
> Since GET has no body, guessing it's POST that has issues?

The issue arises if a GET request followed by POST request. So probably this is the case: POST somehow tries to read till timeout, and therefore following GET request is not handled.

**Comment by essen** [comment] 2017-01-31 17:38
I haven't been able to retry this, and am not sure this still applies to master (body reading has changed) so I will be closing this. Thanks!

**Closed by essen** 2017-01-31 17:38 UTC
Labels: Bug
