### ISSUE TITLE
Crash on sending certificate in headers

### ISSUE THREAD

**Issue by rradz** [ninenines/cowboy#1355] opened 2019-02-15 12:45 UTC
Currently Cowboy 2.5 crashes on trying to send a certificate in request header.

Stacktrace:

```
[error] Ranch listener HeaderExampleWeb.Endpoint.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.447.0> exit with reason: {:function_clause, [{:cowboy_http, :parse_hd_value, ["", {:state, #PID<0.333.0>, HeaderExampleWeb.Endpoint.HTTP, #Port<0.22>, :ranch_tcp, :undefined, %{env: %{dispatch: [{:_, [], [{:_, [], Phoenix.Endpoint.Cowboy2Handler, {HeaderExampleWeb.Endpoint, []}}]}]}, stream_handlers: [Plug.Cowboy.Stream]}, %{}, {{127, 0, 0, 1}, 64911}, {{127, 0, 0, 1}, 4000}, :undefined, #Reference<0.2120077447.3493593090.136272>, 1, {:ps_header, "GET", :undefined, "/", "", :"HTTP/1.1", :undefined, :undefined}, 1, :wait, 100, [], []}, %{"accept" => "*/*", "host" => "localhost:4000", "user-agent" => "curl/7.54.0"}, "x-cert", "-----BEGIN CERTIFICATE-----\n    MIID0DCCArigAwIBAgIBATANBgkqhkiG9w0BAQUFADB/MQswCQYDVQQGEwJGUjET\n    MBEGA1UECAwKU29tZS1TdGF0ZTEOMAwGA1UEBwwFUGFyaXMxDTALBgNVBAoMBERp\n    bWkxDTALBgNVBAsMBE5TQlUxEDAOBgNVBAMMB0RpbWkgQ0ExGzAZBgkqhkiG9w0B\n    CQEWDGRpbWlAZGltaS5mcjAeFw0xNDAxMjgyMDM2NTVaFw0yNDAxMjYyMDM2NTVa\n    MFsxCzAJBgNVBAYTAkZSMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJ\n    bnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxFDASBgNVBAMMC3d3dy5kaW1pLmZyMIIB\n    IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvpnaPKLIKdvx98KW68lz8pGa\n    RRcYersNGqPjpifMVjjE8LuCoXgPU0HePnNTUjpShBnynKCvrtWhN+haKbSp+QWX\n    SxiTrW99HBfAl1MDQyWcukoEb9Cw6INctVUN4iRvkn9T8E6q174RbcnwA/7yTc7p\n    1NCvw+6B/aAN9l1G2pQXgRdYC/+G6o1IZEHtWhqzE97nY5QKNuUVD0V09dc5CDYB\n    aKjqetwwv6DFk/GRdOSEd/6bW+20z0qSHpa3YNW6qSp+x5pyYmDrzRIR03os6Dau\n    ZkChSRyc/Whvurx6o85D6qpzywo8xwNaLZHxTQPgcIA5su9ZIytv9LH2E+lSwwID\n    AQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG+EIBDQQfFh1PcGVuU1NMIEdlbmVy\n    YXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQU+tugFtyN+cXe1wxUqeA7X+yS3bgw\n    HwYDVR0jBBgwFoAUhMwqkbBrGp87HxfvwgPnlGgVR64wDQYJKoZIhvcNAQEFBQAD\n    ggEBAIEEmqqhEzeXZ4CKhE5UM9vCKzkj5Iv9TFs/a9CcQuepzplt7YVmevBFNOc0\n    +1ZyR4tXgi4+5MHGzhYCIVvHo4hKqYm+J+o5mwQInf1qoAHuO7CLD3WNa1sKcVUV\n    vepIxc/1aHZrG+dPeEHt0MdFfOw13YdUc2FH6AqEdcEL4aV5PXq2eYR8hR4zKbc1\n    fBtuqUsvA8NWSIyzQ16fyGve+ANf6vXvUizyvwDrPRv/kfvLNa3ZPnLMMxU98Mvh\n    PXy3PkB8++6U4Y3vdk2Ni2WYYlIls8yqbM"], [file: '/Users/rafal.radziszewski/Development/src/rradz/header_example/deps/cowboy/src/cowboy_http.erl', line: 586]}, {:cowboy_http, :parse, 2, [file: '/Users/rafal.radziszewski/Development/src/rradz/header_example/deps/cowboy/src/cowboy_http.erl', line: 294]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
```

Environement: 
- Elixir 1.7.3
- OTP 21.1
- Phoenix 1.4
- Cowboy 2.5

Steps to reproduce:
1. Start a default phoenix project (sorry, I don't know enough Erlang to reproduce natively), it should expose a default web root "/". Run the project with "mix phx.server"
2. Perform following curl:
```
 curl -H "x-cert:-----BEGIN CERTIFICATE-----
                              MIID0DCCArigAwIBAgIBATANBgkqhkiG9w0BAQUFADB/MQswCQYDVQQGEwJGUjET
                              MBEGA1UECAwKU29tZS1TdGF0ZTEOMAwGA1UEBwwFUGFyaXMxDTALBgNVBAoMBERp
                              bWkxDTALBgNVBAsMBE5TQlUxEDAOBgNVBAMMB0RpbWkgQ0ExGzAZBgkqhkiG9w0B
                              CQEWDGRpbWlAZGltaS5mcjAeFw0xNDAxMjgyMDM2NTVaFw0yNDAxMjYyMDM2NTVa
                              MFsxCzAJBgNVBAYTAkZSMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJ
                              bnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxFDASBgNVBAMMC3d3dy5kaW1pLmZyMIIB
                              IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvpnaPKLIKdvx98KW68lz8pGa
                              RRcYersNGqPjpifMVjjE8LuCoXgPU0HePnNTUjpShBnynKCvrtWhN+haKbSp+QWX
                              SxiTrW99HBfAl1MDQyWcukoEb9Cw6INctVUN4iRvkn9T8E6q174RbcnwA/7yTc7p
                              1NCvw+6B/aAN9l1G2pQXgRdYC/+G6o1IZEHtWhqzE97nY5QKNuUVD0V09dc5CDYB
                              aKjqetwwv6DFk/GRdOSEd/6bW+20z0qSHpa3YNW6qSp+x5pyYmDrzRIR03os6Dau
                              ZkChSRyc/Whvurx6o85D6qpzywo8xwNaLZHxTQPgcIA5su9ZIytv9LH2E+lSwwID
                              AQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG+EIBDQQfFh1PcGVuU1NMIEdlbmVy
                              YXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQU+tugFtyN+cXe1wxUqeA7X+yS3bgw
                              HwYDVR0jBBgwFoAUhMwqkbBrGp87HxfvwgPnlGgVR64wDQYJKoZIhvcNAQEFBQAD
                              ggEBAIEEmqqhEzeXZ4CKhE5UM9vCKzkj5Iv9TFs/a9CcQuepzplt7YVmevBFNOc0
                              +1ZyR4tXgi4+5MHGzhYCIVvHo4hKqYm+J+o5mwQInf1qoAHuO7CLD3WNa1sKcVUV
                              vepIxc/1aHZrG+dPeEHt0MdFfOw13YdUc2FH6AqEdcEL4aV5PXq2eYR8hR4zKbc1
                              fBtuqUsvA8NWSIyzQ16fyGve+ANf6vXvUizyvwDrPRv/kfvLNa3ZPnLMMxU98Mvh
                              PXy3PkB8++6U4Y3vdk2Ni2WYYlIls8yqbM4327IKmkDc2TimS8u60CT47mKU7aDY
                              cbTV5RDkrlaYwm5yqlTIglvCv7o=
                              -----END CERTIFICATE-----" http://localhost:4000
```

Certificate in curl is example one from docs.vmware.com.

I managed to establish that after you delete certain amount of characters from header it starts working, however it's not solely limited on amount of characters - when I used just regular characters (long string of `a` characters) it managed to handle way longer headers. I tried to debug `parse_hd_value` method, but it proved too difficult for me.

If I can help in any way in resolving this, let me know.

**Comment by essen** [comment] 2019-02-15 12:47
Should probably be `curl -H "x-cert: ----...`, notice the space after the `:` character.

**Comment by rradz** [comment] 2019-02-18 12:46
@essen The space doesn't change anything (I just checked just to make sure). If you look at the stacktrace(I see it's terribly formatted on GH) you can notice that certificate header is parsed only to some point, so there is something wrong with parsing going on.

We actually noticed the problem once we updated Phoenix and Cowboy on our production app and suddenly started getting errors due to certificates. I can therefore reasonably say that this is a regression comparing to Cowboy 1. Once again, I'm happy to help in resolving issue if you point me out to what I could do(my Erlang is reading-only and not that great with that neither).

**Comment by essen** [comment] 2019-02-18 14:37
Ah I see the problem. The issue is not obvious because Cowboy has a limited number of checks so it crashes in a non-obvious way.

The problem is that your header value is invalid. Line breaks `\n` are not allowed in field values, and I suppose Cowboy was made a little more strict between 1.x and 2.x. I would strongly suggest reconsidering the way you pass client certificate information forward to avoid this issue. Proxies typically extract and send only minimal information forward for example, not the entire certificate.

**Comment by essen** [comment] 2019-04-03 12:02
Closing, thanks!

**Closed by essen** 2019-04-03 12:02 UTC
