### ISSUE TITLE
How to disable the flow control or keep maintaining the same window size easily?

### ISSUE THREAD

**Issue by colachengexo** [ninenines/cowboy#1369] opened 2019-04-12 02:45 UTC
Hi author!

We have a component with Cowboy 2.6.1 for internal communication through http2. The client and server are in the same machine. The problem is, client-side will reuse the connection (Gun as the client) in the pool and sometime later we will get this error `{connection_error,flow_control_error,'The flow control window must not be greater than 2^31-1. (RFC7540 6.9.1)'}` in the client.

After more investigation about this, I found the default cowboy_stream_h will not send the window_update immediately instead of sending back window_update after a while the amount according to the length(default 8000000) option in the cowboy_req:read_body_opts(). It will cause the flow_control window on the upward trend until reach 2^31-1 then get the error.  I think because of this [function clause](https://github.com/ninenines/cowboy/blob/2.6.1/src/cowboy_stream_h.erl#L185) in the default stream handler.

I found the elixir grpc library have this [grpc_stream_h.erl](https://github.com/elixir-grpc/grpc/blob/master/src/grpc_stream_h.erl) implementation. It will maintain the same window. But the code base seems old (like Cowboy 2.4).

Do you have any suggestion about this or any configuration option in Cowboy or Gun can tune this?

Thanks!

**Comment by essen** [comment] 2019-04-12 06:53
I think the problem is rather that Cowboy is naively sending the length here: https://github.com/ninenines/cowboy/blob/2.6.1/src/cowboy_http2.erl#L564

It should just ensure that there's a large enough window and send the difference `Length -CurrentWindow` (if it's positive) instead, I think.

**Comment by colachengexo** [comment] 2019-04-12 10:28
Sorry, I am not sure your meaning. You mean prevent Cowboy will not send the size to let client window size over the limit? Could you explain more about it? Thanks.

Another question is when this case happens (read_body_length=auto)?
https://github.com/ninenines/cowboy/blob/2.6.1/src/cowboy_stream_h.erl#L96
Because of I saw this case will prepare `{flow, byte_size(Data)}` it means the client will receive window_update immediately. But I will not hit this clause at all.

By the way, do you think this custom stream handler is ok to deal with this problem?

**Comment by essen** [comment] 2019-04-12 10:46
When a handler wants to read 8MB of data Cowboy only needs to increase the window up to 8MB to receive the data. Cowboy may want to increase it a little past 8MB to allow buffering to occur as well. So Cowboy should never set the window to more than 8MB + configurable value in this example. What this means for the connection-wide window is that it needs to keep track of the window size it really needs to fulfill the flow requirements of all existing streams and to never increase the window past this size + configurable value.

Auto is currently being used internally for example for Websocket over HTTP/2 but will be available to users in a future release. It's more for open-ended request bodies though, not for normal requests, and you have to deal with messages asynchronously rather than `cowboy_req:read_body` doing it for you. It is most likely not safe to use at this time because of flooding concerns. To make it better flow should be sent after processing of the data is completed, not immediately when the data is received.

**Comment by essen** [comment] 2019-04-12 10:49
Oh, and no, this isn't something stream handlers need to be concerned with.

**Comment by colachengexo** [comment] 2019-04-12 11:11
I understood now. Thank you for your explanation.

I base on your thought and have this commit. Is correct?
https://github.com/colachengexo/cowboy/commit/9037f60ae4e6ccaef92e5ca631205a5bb103f3f0

**Comment by essen** [comment] 2019-04-12 13:31
Not sure but you're welcome to try and see if it fixes your problem. It should certainly help. Also note that the `get_window` you mention should also receive `StreamID` as an argument.

**Comment by colachengexo** [comment] 2019-04-12 16:45
It will fix our problem after I try. Thanks.

I created two PR (cowboy and cowlib) for this issue. Please review it. Thanks!
https://github.com/ninenines/cowboy/pull/1370
https://github.com/ninenines/cowlib/pull/81

**Comment by essen** [comment] 2019-08-29 10:01
Please see https://github.com/ninenines/cowboy/pull/1393#issuecomment-526115825 for further discussion and what I'm thinking of implementing (this should fix this and other issues).

**Comment by essen** [comment] 2019-09-02 13:04
I've opened two PRs to add heuristics to fix issues and greatly improve WINDOW_UPDATE handling. Please take a look: https://github.com/ninenines/cowlib/pull/87 #1400 

I will document the new options later today or on Thursday.

**Comment by essen** [comment] 2019-09-05 12:10
Fixed via ninenines/cowboy#1400 and ninenines/cowlib#87. Closing, thanks!

**Closed by essen** 2019-09-05 12:10 UTC
