### ISSUE TITLE
PUT when resource doesn't exist goes to previously_existed instead of is_conflict?

### ISSUE THREAD

**Issue by building39** [ninenines/cowboy#827] opened 2015-05-19 19:33 UTC
If I read the flowchart correctly, when doing a PUT request I should expect the flow to go to is_conflict when the resource does not exist. Instead, it goes to moved_permanently, without going through  previously_existed first. 

Is the flowchart (http://ninenines.eu/docs/en/cowboy/HEAD/guide/rest_flowcharts/) up-to-date?
Or am I misreading the intent?

Thanks

**Comment by essen** [comment] 2015-05-19 19:44
Do you have an example module?

**Comment by building39** [comment] 2015-05-27 14:30
I wrote a handler module that does nothing more than log entry into each of the handler callbacks. The returns from the callbacks are hard-coded to provide the path I want to see - in the PUT example, resource_exists/2 returns false. The next callback that appears is moved_permanently/2, followed by is_conflict/2 and content_types_accepted/2. The surprise here is moved_permanently/2, which is not shown in the PUT/POST/PATCH flowchart for method PUT.

handler code:

`-module(example_handler).
-compile([{parse_transform, lager_transform}]).

-export([init/3]).
-export([allowed_methods/2,
         allow_missing_post/2,
         content_types_accepted/2,
         content_types_provided/2,
         delete_completed/2,
         delete_resource/2,
         expires/2,
         forbidden/2,
         from_text_plain/2,
         generate_etag/2,
         is_authorized/2,
         is_conflict/2,
         known_methods/2,
         languages_provided/2,
         last_modified/2,
         malformed_request/2,
         moved_permanently/2,
         moved_temporarily/2,
         multiple_choices/2,
         options/2,
         previously_existed/2,
         resource_exists/2,
         service_available/2,
         to_text_plain/2,
	 uri_too_long/2,
         valid_content_headers/2,
         valid_entity_length/2,
         variances/2
        ]).

init(_, _Req, _Opts) ->
    lager:info("initing..."),
    {upgrade, protocol, cowboy_rest}.

allowed_methods(Req, State) ->
    lager:info("Entry allowed_methods"),
    {[<<"GET">>, <<"PUT">>, <<"POST">>, <<"HEAD">>, <<"DELETE">>], Req, State}.

allow_missing_post(Req, State) ->
    lager:info("Entry allow_missing_post"),
    {true, Req, State}.

content_types_accepted(Req, State) ->
    lager:info("Entry content_types_accepted"),
    {[{{<<"text">>, <<"plain">>, '*'}, from_text_plain} ], Req, State}.

content_types_provided(Req, State) ->
    lager:info("Entry content_types_provided"),
    {[{{<<"text">>, <<"plain">>, '*'}, to_text_plain} ], Req, State}.

delete_completed(Req, State) ->
    lager:info("Entry delete_completed"),
    {true, Req, State}.

delete_resource(Req, State) ->
    lager:info("Entry delete_resources"),
    {true, Req, State}.

expires(Req, State) ->
    lager:info("Entry expires"),
    {true, Req, State}.

forbidden(Req, State) ->
    lager:info("Entry forbidden"),
    {false, Req, State}.
    
from_text_plain(Req, State) ->
    lager:info("Entry from_text_plain"),
    {true, Req, State}.
    
generate_etag(Req, State) ->
    lager:info("Entry generate_etag"),
    {undefined, Req, State}.
    
is_authorized(Req, State) ->
    lager:info("Entry is_authorized"),
    {true, Req, State}.

is_conflict(Req, State) ->
    lager:info("Entry is_conflict"),
    {false, Req, State}.

known_methods(Req, State) ->
    lager:info("Entry known_methods"),
    {[<<"GET">>, <<"HEAD">>, <<"POST">>, <<"PUT">>, <<"PATCH">>, <<"DELETE">>, <<"OPTIONS">>], Req, State}.

languages_provided(Req, State) ->
    lager:info("Entry languages_provided"),
    {[undefined], Req, State}.

last_modified(Req, State) ->
    lager:info("Entry last_modified"),
    {undefined, Req, State}.

malformed_request(Req, State) ->
    lager:info("Entery malformed_request"),
    {false, Req, State}.

moved_permanently(Req, State) ->
    lager:info("Entry moved permanently"),
    {false, Req, State}.

moved_temporarily(Req, State) ->
    lager:info("Entry moved temporarily"),
    {false, Req, State}.

multiple_choices(Req, State) ->
    lager:info("Entry multiple_choices"),
    {false, Req, State}.

options(Req, State) ->
    lager:info("Entry options"),
    {ok, Req, State}.

previously_existed(Req, State) ->
    lager:info("Entry previously_existed"),
    {false, Req, State}.

resource_exists(Req, State) ->
    lager:info("Entry resource_exists"),
    {false, Req, State}.
    
service_available(Req, State) ->
    lager:info("Entry service_available"),
    {true, Req, State}.
    
to_text_plain(Req, State) ->
    lager:info("Entry to_text_plain"),
    {Pid, _Opts} = State,
    {<<"Some text">>, Req, Pid}.

uri_too_long(Req, State) ->
    lager:info("Entry uri_too_long"),
    {false, Req, State}.
    
valid_content_headers(Req, State) ->
    lager:info("Entry valid_content_headers"),
    {true, Req, State}.
    
valid_entity_length(Req, State) ->
    lager:info("Entry valid_entity_length"),
    {true, Req, State}.
    
variances(Req, State) ->
    lager:info("Entry variances"),
    {[], Req, State}.
    `

**Comment by essen** [comment] 2015-05-27 14:40
Right it looks like an oversight in the diagram. This is the intended behavior though.

I will fix the diagram at some point before 2.0. Thanks!

**Comment by building39** [comment] 2015-06-03 15:01
Cool!

**Comment by building39** [comment] 2015-06-03 15:01
Closing

**Comment by essen** [comment] 2015-06-03 15:07
Please keep open so I don't forget though. :-)

**Comment by essen** [comment] 2019-10-06 10:50
I've done it in my local copy to be pushed soon. The corrected diagram will be part of the 2.7 documentation. Thanks!

**Closed by essen** 2019-10-06 10:50 UTC
Labels: Bug
