### ISSUE TITLE
With {inet_backend, socket} mode, after http request closed, gen_tcp_socket:init/1 process still alive

### ISSUE THREAD

**Issue by dogtapdsd** [ninenines/cowboy#1533] opened 2021-08-16 09:08 UTC
It was testing in otp 24,  after one http handle  execute normaly,  I found the 'gen_tcp_socket' process wasn't terminate in Observer's "Processes" tab monitor. this also happen in "cowboy_websocket" module.
May be related to "gen_tcp:shutdown/2"?

**Comment by essen** [comment] 2021-08-16 09:50
Closing because this is best handled in the existing Ranch ticket or PR for the time being.

If you think shutdown is the problem please experiment and try to reproduce a small example that can be sent to OTP for fixing.

**Closed by essen** 2021-08-16 09:50 UTC
