### ISSUE TITLE
cowboy_req:read_urlencoded_body exit(timeout)

### ISSUE THREAD

**Issue by nestor5** [ninenines/cowboy#1168] opened 2017-05-25 09:59 UTC
My cowboy http non-stream handler does the following:

`cowboy_req:read_urlencoded_body(Req0)`

Everyday the handler is called about 1 million times, and every day I get several exit:timeout from the above code:

```
{error_report,<0.8459.3>,
 {<0.13880.3>,crash_report,
  [[{initial_call,
     {cowboy_stream_h,proc_lib_hack,
      [Argument__1,Argument__2,Argument__3]}},
    {pid,<0.13880.3>},
    {registered_name,[]},
    {error_info,
     {exit,
      {timeout,
       [{cowboy_req,read_body,2,
         [{file,"src/cowboy_req.erl"},{line,438}]},
        {cowboy_req,read_urlencoded_body,2,
         [{file,"src/cowboy_req.erl"},{line,454}]},
        {nbserv_http_handler,handle_event_modify,2,
         [{file,"src/nbserv_http_handler.erl"},{line,144}]},
        {nbserv_http_handler,init,2,
         [{file,"src/nbserv_http_handler.erl"},{line,79}]},
        {cowboy_handler,execute,2,
         [{file,"src/cowboy_handler.erl"},{line,37}]},
        {cowboy_stream_h,execute,3,
         [{file,"src/cowboy_stream_h.erl"},{line,178}]},
        {cowboy_stream_h,proc_lib_hack,3,
         [{file,"src/cowboy_stream_h.erl"},{line,163}]},
        {proc_lib,init_p_do_apply,3,
         [{file,"proc_lib.erl"},{line,247}]}]},
      [{cowboy_stream_h,proc_lib_hack,3,
        [{file,"src/cowboy_stream_h.erl"},{line,168}]},
       {proc_lib,init_p_do_apply,3,
        [{file,"proc_lib.erl"},{line,247}]}]}},
    {ancestors,[<0.13879.3>,<0.11631.3>,<0.11630.3>,ranch_sup,<0.8460.3>]},
    {messages,[]},
    {links,[]},
    {dictionary,[]},
    {trap_exit,false},
    {status,running},
    {heap_size,987},
    {stack_size,27},
    {reductions,306}],
   []]}}
```

**Comment by csrl** [comment] 2017-06-02 19:01
We also have this issue repeatedly - so we wrap the call in a catch handler to deal with it, and currently accept the request failure rate.

Our research into it, we find that  read_urlencoded_body/1 defaults to a 5000 ms period.  We've played with increasig that timeout by calling read_urlencoded_body/2 with appropriate options, however we find that increasing the timeout duration doesn't noticeably reduce the occurrence of the 'timeout'.  And since in our case the entire http request should fit into a single tcp frame, it isn't like the timeout is from waiting for the data to actually be sent by the client.   So something is a bottleneck/starving for a still unknown reason to us.

**Comment by essen** [comment] 2017-06-28 17:07
Can you try again? I fixed something in cad3e3f63d96559f16ee90e661a29063d0b3fc80 that might be related.

**Comment by csrl** [comment] 2017-06-29 08:36
We aren't using http2, so I guess that commit would not affect us?

**Comment by essen** [comment] 2017-06-29 08:57
OK. Then it could be a bug, because that timeout is only triggered when something is going wrong. Slow rate would result in less or empty data being returned. A way to reproduce would be great though. :-)

**Comment by essen** [comment] 2018-05-16 13:07
Does this still occur? And can you post more recent error reports? Thanks.

**Comment by csrl** [comment] 2018-05-16 18:05
I haven't been working on the project that uses this for a while.  At a quick glance, it doesn't look like the project has been updated to recent version of cowboy for a while.  But I'll poke our internal tracker on this issue and see if anyone responds.

**Comment by essen** [comment] 2019-10-03 16:23
Since the issue is old and there's been no new reports I'll close this for now. If someone still has the issue then please reopen or open a new ticket with as much details as possible. Thanks!

**Closed by essen** 2019-10-03 16:23 UTC
