### ISSUE TITLE
Crash with invalid URL

### ISSUE THREAD

**Issue by rvangraan** [ninenines/cowboy#1199] opened 2017-08-03 09:24 UTC
Cowboy crashes when a request URL contains invalid characters. Should't it just return a `400 - Bad Request`?

```
{'EXIT',<0.8098.0>,
    {function_clause,
        [{cow_uri,urldecode,
             [<<\"[0;31\">>,<<\"Roses are \\e\">>],
             [{file,
                  \"/drone/src/github.com/http/_build/default/lib/cowlib/src/cow_uri.erl\"},
              {line,26}]},
         {cowboy_router,'-split_path/2-lc$^1/1-1-',1,
             [{file,
                  \"/drone/src/github.com/http/_build/default/lib/cowboy/src/cowboy_router.erl\"},
              {line,323}]},
         {cowboy_router,split_path,2,
             [{file,
                  \"/drone/src/github.com/http/_build/default/lib/cowboy/src/cowboy_router.erl\"},
              {line,323}]},
         {cowboy_router,split_path,2,
             [{file,
                  \"/drone/src/github.com/http/_build/default/lib/cowboy/src/cowboy_router.erl\"},
              {line,326}]},
         {cowboy_router,match_path,4,
             [{file,
                  \"/drone/src/github.com/http/_build/default/lib/cowboy/src/cowboy_router.erl\"},
              {line,271}]},
         {cowboy_router,execute,2,
             [{file,
                  \"/drone/src/github.com/http/_build/default/lib/cowboy/src/cowboy_router.erl\"},
              {line,163}]},
         {cowboy_stream_h,execute,3,
             [{file,
                  \"/drone/src/github.com/http/_build/default/lib/cowboy/src/cowboy_stream_h.erl\"},
              {line,178}]},
         {cowboy_stream_h,proc_lib_hack,3,
             [{file,
                  \"/drone/src/github.com/http/_build/default/lib/cowboy/src/cowboy_stream_h.erl\"},
              {line,163}]}]}}
```

**Comment by essen** [comment] 2017-08-03 10:12
Yes.

**Comment by essen** [comment] 2017-10-02 13:15
This is a duplicate of #936. Closing this in favor. I will fix it now.

**Closed by essen** 2017-10-02 13:15 UTC
